/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.karaoke.ui.thongke;

import com.karaoke.helper.ExportExcel;
import com.karaoke.helper.InHoaDon;
import com.karaoke.helper.JDBCHelper;
import com.karaoke.helper.JOptionPaneHelper;
import com.karaoke.helper.XuLy;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PS08241 - Nguyen Nhat Thanh
 */
public class TKHoaDonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TKHoaDon
     */
    public TKHoaDonJPanel() {
        initComponents();
        txtFromDate.setLocale(new Locale("vi", "VIETNAM"));
        txtFromDate.setDateFormatString("dd/MM/yyyy");
        txtToDate.setLocale(new Locale("vi", "VIETNAM"));
        txtToDate.setDateFormatString("dd/MM/yyyy");
        txtFromDate.setDate(new Date());
        txtToDate.setDate(new Date());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlThongKe = new javax.swing.JPanel();
        pnlDate = new javax.swing.JPanel();
        lblNamSinh = new javax.swing.JLabel();
        txtFromDate = new com.toedter.calendar.JDateChooser();
        lblNamSinh2 = new javax.swing.JLabel();
        txtToDate = new com.toedter.calendar.JDateChooser();
        btnFilter = new javax.swing.JButton();
        btnExcel = new javax.swing.JButton();
        lblChonNgay1 = new javax.swing.JLabel();
        pnlChiTiet = new javax.swing.JPanel();
        lblTongTienGio = new javax.swing.JLabel();
        lblTongTienGio_name = new javax.swing.JLabel();
        lblTongTienDV = new javax.swing.JLabel();
        lblTongTienDV_name = new javax.swing.JLabel();
        lblTongTienGiam = new javax.swing.JLabel();
        lblTongTienGiam_name = new javax.swing.JLabel();
        lblTongThucThu = new javax.swing.JLabel();
        lblTongTienGiam_name1 = new javax.swing.JLabel();
        pnlTable = new javax.swing.JPanel();
        lblNamSinh5 = new javax.swing.JLabel();
        scrTable = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        scrTable1 = new javax.swing.JScrollPane();
        tblDichVu = new javax.swing.JTable();
        lblNamSinh6 = new javax.swing.JLabel();
        btnInHD = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1050, 690));
        setMinimumSize(new java.awt.Dimension(1050, 690));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1050, 690));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlThongKe.setBackground(new java.awt.Color(204, 204, 255));
        pnlThongKe.setMaximumSize(new java.awt.Dimension(1200, 590));
        pnlThongKe.setMinimumSize(new java.awt.Dimension(1200, 590));
        pnlThongKe.setOpaque(false);
        pnlThongKe.setPreferredSize(new java.awt.Dimension(1200, 590));
        pnlThongKe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDate.setBackground(new java.awt.Color(204, 204, 255));
        pnlDate.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlDate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNamSinh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNamSinh.setText("Từ ngày:");
        pnlDate.add(lblNamSinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 70, 30));

        txtFromDate.setForeground(new java.awt.Color(102, 0, 0));
        txtFromDate.setDateFormatString("dd/MM/yyyy");
        txtFromDate.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        pnlDate.add(txtFromDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 180, 30));

        lblNamSinh2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNamSinh2.setText("Đến ngày:");
        pnlDate.add(lblNamSinh2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 70, 30));

        txtToDate.setForeground(new java.awt.Color(102, 0, 0));
        txtToDate.setDateFormatString("dd/MM/yyyy");
        txtToDate.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        pnlDate.add(txtToDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 180, 30));

        btnFilter.setBackground(new java.awt.Color(255, 255, 255));
        btnFilter.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFilter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/karaoke/images/icon/filter.png"))); // NOI18N
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });
        pnlDate.add(btnFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 50, 50));

        btnExcel.setBackground(new java.awt.Color(255, 255, 255));
        btnExcel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/karaoke/images/icon/excel.png"))); // NOI18N
        btnExcel.setText("Trích xuất Excel");
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });
        pnlDate.add(btnExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 180, 40));

        lblChonNgay1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblChonNgay1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblChonNgay1.setText("Chọn ngày cần thống kê");
        pnlDate.add(lblChonNgay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 30));

        pnlThongKe.add(pnlDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 280, 220));

        pnlChiTiet.setBackground(new java.awt.Color(204, 204, 255));
        pnlChiTiet.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlChiTiet.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTongTienGio.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        lblTongTienGio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pnlChiTiet.add(lblTongTienGio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 140, 30));

        lblTongTienGio_name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTongTienGio_name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTongTienGio_name.setText("Tổng tiền giờ:");
        pnlChiTiet.add(lblTongTienGio_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 100, 30));

        lblTongTienDV.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        lblTongTienDV.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pnlChiTiet.add(lblTongTienDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 140, 30));

        lblTongTienDV_name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTongTienDV_name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTongTienDV_name.setText("Tổng tiền dịch vụ:");
        pnlChiTiet.add(lblTongTienDV_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 120, 30));

        lblTongTienGiam.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        lblTongTienGiam.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pnlChiTiet.add(lblTongTienGiam, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 140, 30));

        lblTongTienGiam_name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTongTienGiam_name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTongTienGiam_name.setText("Tổng tiền giảm:");
        pnlChiTiet.add(lblTongTienGiam_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 100, 30));

        lblTongThucThu.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        lblTongThucThu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pnlChiTiet.add(lblTongThucThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 140, 30));

        lblTongTienGiam_name1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTongTienGiam_name1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTongTienGiam_name1.setText("Tổng thực thu:");
        pnlChiTiet.add(lblTongTienGiam_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 100, 30));

        pnlThongKe.add(pnlChiTiet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 280, 340));

        pnlTable.setBackground(new java.awt.Color(204, 204, 255));
        pnlTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlTable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNamSinh5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNamSinh5.setText("Danh sách Hóa Đơn");
        pnlTable.add(lblNamSinh5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, 30));

        tblHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã", "Phòng", "Tiền Giờ", "Tiền DV", "Tổng Tiền", "Giảm Giá", "Thành Tiền", "Ngày Thanh Toán", "Mã User"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoaDon.setGridColor(new java.awt.Color(255, 255, 255));
        tblHoaDon.setRowHeight(25);
        tblHoaDon.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tblHoaDon.setSelectionForeground(new java.awt.Color(0, 0, 204));
        tblHoaDon.setShowHorizontalLines(false);
        tblHoaDon.setShowVerticalLines(false);
        tblHoaDon.getTableHeader().setReorderingAllowed(false);
        scrTable.setViewportView(tblHoaDon);
        if (tblHoaDon.getColumnModel().getColumnCount() > 0) {
            tblHoaDon.getColumnModel().getColumn(0).setMinWidth(50);
            tblHoaDon.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblHoaDon.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        pnlTable.add(scrTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 700, 210));

        tblDichVu.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên DV", "SL", "Đơn giá", "Thành tiền", "Ngày bán"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDichVu.setGridColor(new java.awt.Color(255, 255, 255));
        tblDichVu.setRowHeight(50);
        tblDichVu.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tblDichVu.setSelectionForeground(new java.awt.Color(0, 0, 204));
        tblDichVu.setShowHorizontalLines(false);
        tblDichVu.setShowVerticalLines(false);
        tblDichVu.getTableHeader().setReorderingAllowed(false);
        scrTable1.setViewportView(tblDichVu);
        if (tblDichVu.getColumnModel().getColumnCount() > 0) {
            tblDichVu.getColumnModel().getColumn(0).setMinWidth(50);
            tblDichVu.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblDichVu.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        pnlTable.add(scrTable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 700, 210));

        lblNamSinh6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNamSinh6.setText("Danh sách Dịch vụ bán ra");
        pnlTable.add(lblNamSinh6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 200, 30));

        btnInHD.setBackground(new java.awt.Color(255, 255, 255));
        btnInHD.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnInHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/karaoke/images/icon/print.png"))); // NOI18N
        btnInHD.setText("IN HÓA ĐƠN");
        btnInHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInHDActionPerformed(evt);
            }
        });
        pnlTable.add(btnInHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 150, 40));

        pnlThongKe.add(pnlTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 740, 570));

        add(pnlThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 690));
    }// </editor-fold>//GEN-END:initComponents

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        // TODO add your handling code here:
        loadHD();
        loadDV();
    }//GEN-LAST:event_btnFilterActionPerformed

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        if (tblHoaDon.getRowCount() > 0) {
            try {
                // TODO add your handling code here:
                ExportExcel.Writer(this, tblHoaDon, tblDichVu);
            } catch (IOException ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JOptionPaneHelper.popup("loi", this, "Lỗi", "Export to Excel");

            }
        } else {
            JOptionPaneHelper.popup("loi", this, "Chưa có dữ liệu", "Export to Excel");

        }

    }//GEN-LAST:event_btnExcelActionPerformed

    private void btnInHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInHDActionPerformed
        // TODO add your handling code here:
        if (tblHoaDon.getSelectedRow() >= 0) {
            inHD(tblHoaDon.getValueAt(tblHoaDon.getSelectedRow(), 1) + "");
        } else {
            JOptionPaneHelper.popup("loi", this, "Chưa chọn Hóa đơn nào", "Lỗi");
        }

    }//GEN-LAST:event_btnInHDActionPerformed


    private void loadHD() {
        tblHoaDon.removeAll();

        try {
            DefaultTableModel table = (DefaultTableModel) tblHoaDon.getModel();
            table.setRowCount(0);
            ResultSet rs = JDBCHelper.executeQuery("SELECT * FROM tk_HoaDon WHERE gioThanhToan BETWEEN ? AND ? ORDER BY gioThanhToan ASC", new SimpleDateFormat("yyyy-MM-dd").format(txtFromDate.getDate()), new SimpleDateFormat("yyyy-MM-dd").format(txtToDate.getDate()) + " 23:59:59");
            int stt = 0;
            while (rs.next()) {
                stt++;
                Object[] row = new Object[]{
                    stt, rs.getString("maHD"), rs.getString("maPhong"), XuLy.xulySo(rs.getString("tienGio")), XuLy.xulySo(rs.getString("tienDV")), XuLy.xulySo(rs.getString("tongTien")), XuLy.xulySo(rs.getString("tienGiamGia")), XuLy.xulySo(rs.getString("thanhTien")), rs.getString("gioThanhToan"), rs.getString("maUser"),};
                table.addRow(row);
            }
            rs = JDBCHelper.executeQuery("SELECT SUM(tienGio),SUM(tienDV), SUM(tienGiamGia),SUM(thanhTien) FROM tk_HoaDon WHERE gioThanhToan BETWEEN ? AND ? ", new SimpleDateFormat("yyyy-MM-dd").format(txtFromDate.getDate()), new SimpleDateFormat("yyyy-MM-dd").format(txtToDate.getDate()) + " 23:59:59");
            if (rs.next()) {
                if (rs.getString(1) != null) {
                    lblTongTienGio.setText(XuLy.xulySo(rs.getString(1)));

                }
                if (rs.getString(2) != null) {
                    lblTongTienDV.setText(XuLy.xulySo(rs.getString(2)));

                }
                if (rs.getString(3) != null) {
                    lblTongTienGiam.setText(XuLy.xulySo(rs.getString(3)));

                }
                if (rs.getString(4) != null) {
                    lblTongThucThu.setText(XuLy.xulySo(rs.getString(4)));

                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
        }
        tblHoaDon.setName("HD tu " + new SimpleDateFormat("dd.MM.yyyy").format(txtFromDate.getDate()) + " den " + new SimpleDateFormat("dd.MM.yyyy").format(txtToDate.getDate()));

    }

    private void loadDV() {
        tblDichVu.removeAll();
        try {
            DefaultTableModel table = (DefaultTableModel) tblDichVu.getModel();
            table.setRowCount(0);
            ResultSet rs = JDBCHelper.executeQuery("SELECT * FROM tk_DichVu WHERE gioThanhToan BETWEEN ? AND ? ORDER BY gioThanhToan ASC", new SimpleDateFormat("yyyy-MM-dd").format(txtFromDate.getDate()), new SimpleDateFormat("yyyy-MM-dd").format(txtToDate.getDate()) + " 23:59:59");
            int stt = 0;
            while (rs.next()) {
                stt++;
                String url = "C:\\ProgramData\\KaraTNQ\\images\\service\\" + rs.getString("hinh");                
                String hinh = ("<html><b><font color=blue> <img src=\"file:" +  "C:\\ProgramData\\KaraTNQ\\images\\service\\" + rs.getString("hinh")+ "\" height=\"30px\" width=\"30px\" align=\"middle\"> ");
                Object[] row = new Object[]{
                    stt, hinh+rs.getString("tenDV"), rs.getString("soLuong"), XuLy.xulySo(rs.getString("giaBan")), XuLy.xulySo(rs.getString("thanhTien")), rs.getString("gioThanhToan")};
                
                table.addRow(row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
        }
        tblDichVu.setName("HDDV tu " + new SimpleDateFormat("dd.MM.yyyy").format(txtFromDate.getDate()) + " den " + new SimpleDateFormat("dd.MM.yyyy").format(txtToDate.getDate()));

    }

    private void inHD(String maHD) {

        if (JOptionPaneHelper.ask(this, "Bạn có muốn trích xuất Chi tiết Hóa đơn " + maHD, "TRÍCH XUẤT HÓA ĐƠN") == 0) {
            InHoaDon.inHoaDon(maHD);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcel;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnInHD;
    private javax.swing.JLabel lblChonNgay1;
    private javax.swing.JLabel lblNamSinh;
    private javax.swing.JLabel lblNamSinh2;
    private javax.swing.JLabel lblNamSinh5;
    private javax.swing.JLabel lblNamSinh6;
    private javax.swing.JLabel lblTongThucThu;
    private javax.swing.JLabel lblTongTienDV;
    private javax.swing.JLabel lblTongTienDV_name;
    private javax.swing.JLabel lblTongTienGiam;
    private javax.swing.JLabel lblTongTienGiam_name;
    private javax.swing.JLabel lblTongTienGiam_name1;
    private javax.swing.JLabel lblTongTienGio;
    private javax.swing.JLabel lblTongTienGio_name;
    private javax.swing.JPanel pnlChiTiet;
    private javax.swing.JPanel pnlDate;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JPanel pnlThongKe;
    private javax.swing.JScrollPane scrTable;
    private javax.swing.JScrollPane scrTable1;
    private javax.swing.JTable tblDichVu;
    private javax.swing.JTable tblHoaDon;
    private com.toedter.calendar.JDateChooser txtFromDate;
    private com.toedter.calendar.JDateChooser txtToDate;
    // End of variables declaration//GEN-END:variables
}
