package com.karaoke.ui;

import java.awt.Color;
import java.awt.Dimension;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import javax.swing.Icon;

/**
 *
 * @author TVD
 */
public class ChiTietPhongJPanel extends javax.swing.JPanel {

    final ScheduledExecutorService svc = Executors.newScheduledThreadPool(1);

    public ChiTietPhongJPanel() {
        initComponents();
        pnlLeft.setBackground(new Color(18,05,88,80));
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoot = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlLeft = new javax.swing.JPanel();
        pnlChiTietHoaDon = new javax.swing.JPanel();
        txtGioVao = new javax.swing.JLabel();
        txtTenPhong = new javax.swing.JLabel();
        scrHoaDon = new javax.swing.JScrollPane();
        pnlHoaDon = new javax.swing.JPanel();
        lblKhachhangchuasudung = new javax.swing.JLabel();
        lblGiaPhong = new javax.swing.JLabel();
        txtGiaPhong = new javax.swing.JLabel();
        lblChitiet = new javax.swing.JLabel();
        lblTienDV = new javax.swing.JLabel();
        lblTienGio = new javax.swing.JLabel();
        txtTienGio = new javax.swing.JLabel();
        txtTongTamTinh = new javax.swing.JLabel();
        lblTongTamTinh = new javax.swing.JLabel();
        btnCapNhat = new javax.swing.JButton();
        btnTinhTien = new javax.swing.JButton();
        lblTenKH = new javax.swing.JLabel();
        lblThoiluong = new javax.swing.JLabel();
        txtThoiluong = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        lblGiovao = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        lblDT = new javax.swing.JLabel();
        txtTienDV = new javax.swing.JLabel();
        btnChuyenPhong = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        pnlRight = new javax.swing.JPanel();
        pnlThanhToan = new javax.swing.JPanel();
        txtTenPhong1 = new javax.swing.JLabel();
        lblTongTien1 = new javax.swing.JLabel();
        lblTienKhachDua = new javax.swing.JLabel();
        num4 = new javax.swing.JButton();
        num0 = new javax.swing.JButton();
        num1 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        num7 = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        lblStatusVoucher = new javax.swing.JLabel();
        txtVoucher = new javax.swing.JTextField();
        lblVoucher = new javax.swing.JLabel();
        num10 = new javax.swing.JButton();
        btnThanhToan = new javax.swing.JButton();
        chkInHoaDon = new javax.swing.JCheckBox();
        chkSMS = new javax.swing.JCheckBox();
        lblTongThanhTien = new javax.swing.JLabel();
        txtTongThanhTien = new javax.swing.JLabel();
        txtTongTienHD = new javax.swing.JLabel();
        txtTienKhachDua = new javax.swing.JLabel();
        pnlDichVu = new javax.swing.JPanel();
        tabbedDV = new javax.swing.JTabbedPane();
        pnlQuickSearch = new javax.swing.JPanel();
        txtQuickSearch = new javax.swing.JTextField();
        lblQuickSearch = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1050, 690));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1050, 690));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRoot.setBackground(new java.awt.Color(255, 255, 255));
        pnlRoot.setMaximumSize(new java.awt.Dimension(1050, 690));
        pnlRoot.setMinimumSize(new java.awt.Dimension(1050, 690));
        pnlRoot.setOpaque(false);
        pnlRoot.setPreferredSize(new java.awt.Dimension(1050, 690));
        pnlRoot.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ĐANG PHÁT TRIỂN LẠI. ĐANG PHÁT TRIỂN LẠI. ĐANG PHÁT TRIỂN LẠI. ĐANG PHÁT TRIỂN LẠI. ĐANG PHÁT TRIỂN LẠI. ĐANG PHÁT TRIỂN LẠI. ĐANG PHÁT TRIỂN LẠI. ĐANG PHÁT TRIỂN LẠI. ");
        pnlRoot.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 1040, 90));

        pnlLeft.setMaximumSize(new java.awt.Dimension(600, 560));
        pnlLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlChiTietHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        pnlChiTietHoaDon.setForeground(new java.awt.Color(0, 102, 51));
        pnlChiTietHoaDon.setMaximumSize(new java.awt.Dimension(525, 560));
        pnlChiTietHoaDon.setMinimumSize(new java.awt.Dimension(525, 560));
        pnlChiTietHoaDon.setOpaque(false);
        pnlChiTietHoaDon.setPreferredSize(new java.awt.Dimension(525, 560));
        pnlChiTietHoaDon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtGioVao.setBackground(new java.awt.Color(51, 51, 51));
        txtGioVao.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        txtGioVao.setForeground(new java.awt.Color(51, 51, 51));
        txtGioVao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtGioVao.setText("20/03/2019 08:30:34");
        txtGioVao.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlChiTietHoaDon.add(txtGioVao, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 330, 20));

        txtTenPhong.setBackground(new java.awt.Color(51, 51, 51));
        txtTenPhong.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtTenPhong.setForeground(new java.awt.Color(255, 0, 0));
        txtTenPhong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTenPhong.setText("Phòng RM0004");
        pnlChiTietHoaDon.add(txtTenPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 40));

        scrHoaDon.setBackground(new java.awt.Color(51, 51, 51));
        scrHoaDon.setBorder(null);
        scrHoaDon.setMaximumSize(new java.awt.Dimension(450, 250));
        scrHoaDon.setMinimumSize(new java.awt.Dimension(450, 250));
        scrHoaDon.setPreferredSize(new java.awt.Dimension(450, 250));

        pnlHoaDon.setForeground(new java.awt.Color(153, 153, 255));

        lblKhachhangchuasudung.setFont(new java.awt.Font("Cambria", 3, 12)); // NOI18N
        lblKhachhangchuasudung.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKhachhangchuasudung.setText("(Khách hàng chưa sử dụng dịch vụ nào)");
        lblKhachhangchuasudung.setMaximumSize(new java.awt.Dimension(300, 20));
        lblKhachhangchuasudung.setMinimumSize(new java.awt.Dimension(300, 20));
        lblKhachhangchuasudung.setPreferredSize(new java.awt.Dimension(300, 20));
        pnlHoaDon.add(lblKhachhangchuasudung);

        scrHoaDon.setViewportView(pnlHoaDon);

        pnlChiTietHoaDon.add(scrHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 470, 220));

        lblGiaPhong.setBackground(new java.awt.Color(51, 51, 51));
        lblGiaPhong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGiaPhong.setForeground(new java.awt.Color(0, 102, 153));
        lblGiaPhong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGiaPhong.setText("Giá phòng (1h):");
        pnlChiTietHoaDon.add(lblGiaPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 130, 20));

        txtGiaPhong.setBackground(new java.awt.Color(51, 51, 51));
        txtGiaPhong.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        txtGiaPhong.setForeground(new java.awt.Color(51, 51, 51));
        txtGiaPhong.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtGiaPhong.setText("190,000đ");
        txtGiaPhong.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlChiTietHoaDon.add(txtGiaPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 290, 20));

        lblChitiet.setBackground(new java.awt.Color(51, 51, 51));
        lblChitiet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblChitiet.setForeground(new java.awt.Color(0, 102, 153));
        lblChitiet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChitiet.setText("CHI TIẾT DỊCH VỤ SỬ DỤNG");
        pnlChiTietHoaDon.add(lblChitiet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 560, 30));

        lblTienDV.setBackground(new java.awt.Color(51, 51, 51));
        lblTienDV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTienDV.setForeground(new java.awt.Color(0, 102, 153));
        lblTienDV.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTienDV.setText("Tổng tiền dịch vụ:");
        pnlChiTietHoaDon.add(lblTienDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 130, 30));

        lblTienGio.setBackground(new java.awt.Color(51, 51, 51));
        lblTienGio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTienGio.setForeground(new java.awt.Color(0, 102, 153));
        lblTienGio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTienGio.setText("Tổng tiền giờ:");
        pnlChiTietHoaDon.add(lblTienGio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 130, 30));

        txtTienGio.setBackground(new java.awt.Color(51, 51, 51));
        txtTienGio.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtTienGio.setForeground(new java.awt.Color(255, 0, 0));
        txtTienGio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtTienGio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlChiTietHoaDon.add(txtTienGio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 230, 30));

        txtTongTamTinh.setBackground(new java.awt.Color(51, 51, 51));
        txtTongTamTinh.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtTongTamTinh.setForeground(new java.awt.Color(255, 0, 0));
        txtTongTamTinh.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtTongTamTinh.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlChiTietHoaDon.add(txtTongTamTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 230, 30));

        lblTongTamTinh.setBackground(new java.awt.Color(51, 51, 51));
        lblTongTamTinh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTongTamTinh.setForeground(new java.awt.Color(0, 102, 153));
        lblTongTamTinh.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTongTamTinh.setText("Tổng tạm tính:");
        pnlChiTietHoaDon.add(lblTongTamTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 160, 30));

        btnCapNhat.setBackground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(0, 102, 153));
        btnCapNhat.setText("CẬP NHẬT");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        pnlChiTietHoaDon.add(btnCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 110, 40));

        btnTinhTien.setBackground(new java.awt.Color(255, 255, 255));
        btnTinhTien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTinhTien.setForeground(new java.awt.Color(0, 102, 153));
        btnTinhTien.setText("TÍNH TIỀN");
        btnTinhTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhTienActionPerformed(evt);
            }
        });
        pnlChiTietHoaDon.add(btnTinhTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 110, 40));

        lblTenKH.setBackground(new java.awt.Color(51, 51, 51));
        lblTenKH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTenKH.setForeground(new java.awt.Color(0, 102, 153));
        lblTenKH.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTenKH.setText("Khách hàng:");
        pnlChiTietHoaDon.add(lblTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 80, 20));

        lblThoiluong.setBackground(new java.awt.Color(51, 51, 51));
        lblThoiluong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblThoiluong.setForeground(new java.awt.Color(0, 102, 153));
        lblThoiluong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblThoiluong.setText("Thời lượng:");
        pnlChiTietHoaDon.add(lblThoiluong, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 100, 20));

        txtThoiluong.setBackground(new java.awt.Color(51, 51, 51));
        txtThoiluong.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        txtThoiluong.setForeground(new java.awt.Color(51, 51, 51));
        txtThoiluong.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtThoiluong.setText("02 giờ 30 phút");
        txtThoiluong.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlChiTietHoaDon.add(txtThoiluong, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 310, 20));

        txtTenKH.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        txtTenKH.setForeground(new java.awt.Color(51, 51, 51));
        txtTenKH.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTenKH.setText("TRỊNH TỐ NHƯ");
        txtTenKH.setMaximumSize(new java.awt.Dimension(200, 30));
        txtTenKH.setMinimumSize(new java.awt.Dimension(200, 30));
        txtTenKH.setPreferredSize(new java.awt.Dimension(200, 30));
        txtTenKH.setRequestFocusEnabled(false);
        txtTenKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTenKHMouseClicked(evt);
            }
        });
        pnlChiTietHoaDon.add(txtTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 140, 20));

        lblGiovao.setBackground(new java.awt.Color(51, 51, 51));
        lblGiovao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGiovao.setForeground(new java.awt.Color(0, 102, 153));
        lblGiovao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGiovao.setText("Giờ vào:");
        pnlChiTietHoaDon.add(lblGiovao, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 90, 20));

        txtSDT.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        txtSDT.setForeground(new java.awt.Color(51, 51, 51));
        txtSDT.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSDT.setText("0357991805");
        txtSDT.setMaximumSize(new java.awt.Dimension(200, 30));
        txtSDT.setMinimumSize(new java.awt.Dimension(200, 30));
        txtSDT.setPreferredSize(new java.awt.Dimension(200, 30));
        txtSDT.setRequestFocusEnabled(false);
        txtSDT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSDTMouseClicked(evt);
            }
        });
        pnlChiTietHoaDon.add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 120, 20));

        lblDT.setBackground(new java.awt.Color(51, 51, 51));
        lblDT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDT.setForeground(new java.awt.Color(0, 102, 153));
        lblDT.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDT.setText("SĐT:");
        pnlChiTietHoaDon.add(lblDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 30, 20));

        txtTienDV.setBackground(new java.awt.Color(51, 51, 51));
        txtTienDV.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtTienDV.setForeground(new java.awt.Color(255, 0, 0));
        txtTienDV.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtTienDV.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlChiTietHoaDon.add(txtTienDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 230, 30));

        btnChuyenPhong.setBackground(new java.awt.Color(255, 255, 255));
        btnChuyenPhong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnChuyenPhong.setForeground(new java.awt.Color(0, 102, 153));
        btnChuyenPhong.setText("CHUYỂN");
        btnChuyenPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenPhongActionPerformed(evt);
            }
        });
        pnlChiTietHoaDon.add(btnChuyenPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 110, 40));

        btnHuy.setBackground(new java.awt.Color(255, 255, 255));
        btnHuy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(0, 102, 153));
        btnHuy.setText("HỦY PHÒNG");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        pnlChiTietHoaDon.add(btnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 110, 40));

        pnlLeft.add(pnlChiTietHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 530, 560));

        pnlRoot.add(pnlLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 690));

        pnlRight.setMaximumSize(new java.awt.Dimension(525, 560));
        pnlRight.setMinimumSize(new java.awt.Dimension(525, 560));
        pnlRight.setPreferredSize(new java.awt.Dimension(525, 560));
        pnlRight.setLayout(new java.awt.CardLayout());

        pnlThanhToan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlThanhToan.setMaximumSize(new java.awt.Dimension(400, 230));
        pnlThanhToan.setMinimumSize(new java.awt.Dimension(400, 230));
        pnlThanhToan.setPreferredSize(new java.awt.Dimension(400, 230));
        pnlThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlThanhToanMouseClicked(evt);
            }
        });
        pnlThanhToan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pnlThanhToanKeyReleased(evt);
            }
        });
        pnlThanhToan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTenPhong1.setBackground(new java.awt.Color(51, 51, 51));
        txtTenPhong1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtTenPhong1.setForeground(new java.awt.Color(255, 0, 0));
        txtTenPhong1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTenPhong1.setText("THANH TOÁN HÓA ĐƠN");
        pnlThanhToan.add(txtTenPhong1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 380, 40));

        lblTongTien1.setBackground(new java.awt.Color(51, 51, 51));
        lblTongTien1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTongTien1.setForeground(new java.awt.Color(0, 102, 153));
        lblTongTien1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTongTien1.setText("Tổng tạm tính:");
        pnlThanhToan.add(lblTongTien1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 140, 40));

        lblTienKhachDua.setBackground(new java.awt.Color(51, 51, 51));
        lblTienKhachDua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTienKhachDua.setForeground(new java.awt.Color(0, 102, 153));
        lblTienKhachDua.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTienKhachDua.setText("TIỀN KHÁCH ĐƯA:");
        pnlThanhToan.add(lblTienKhachDua, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 140, 40));

        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });
        pnlThanhToan.add(num4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 40, 40));

        num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num0ActionPerformed(evt);
            }
        });
        pnlThanhToan.add(num0, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 40, 40));

        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });
        pnlThanhToan.add(num1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 40, 40));

        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });
        pnlThanhToan.add(num2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 40, 40));

        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });
        pnlThanhToan.add(num3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 40, 40));

        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });
        pnlThanhToan.add(num5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 40, 40));

        num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num6ActionPerformed(evt);
            }
        });
        pnlThanhToan.add(num6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 40, 40));

        num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num7ActionPerformed(evt);
            }
        });
        pnlThanhToan.add(num7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 40, 40));

        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8ActionPerformed(evt);
            }
        });
        pnlThanhToan.add(num8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 40, 40));

        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num9ActionPerformed(evt);
            }
        });
        pnlThanhToan.add(num9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 40, 40));

        lblStatusVoucher.setBackground(new java.awt.Color(51, 51, 51));
        lblStatusVoucher.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblStatusVoucher.setForeground(new java.awt.Color(0, 102, 153));
        lblStatusVoucher.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlThanhToan.add(lblStatusVoucher, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 270, 20));

        txtVoucher.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtVoucher.setForeground(new java.awt.Color(0, 204, 0));
        txtVoucher.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVoucher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVoucherKeyReleased(evt);
            }
        });
        pnlThanhToan.add(txtVoucher, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 270, 40));

        lblVoucher.setBackground(new java.awt.Color(51, 51, 51));
        lblVoucher.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblVoucher.setForeground(new java.awt.Color(0, 102, 153));
        lblVoucher.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblVoucher.setText("Voucher:");
        pnlThanhToan.add(lblVoucher, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 140, 40));

        num10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num10ActionPerformed(evt);
            }
        });
        pnlThanhToan.add(num10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 40, 80));

        btnThanhToan.setBackground(new java.awt.Color(255, 255, 255));
        btnThanhToan.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnThanhToan.setForeground(new java.awt.Color(0, 102, 153));
        btnThanhToan.setText("THANH TOÁN");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });
        pnlThanhToan.add(btnThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 150, 40));

        chkInHoaDon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkInHoaDon.setForeground(new java.awt.Color(0, 102, 153));
        chkInHoaDon.setText("In Hóa Đơn");
        pnlThanhToan.add(chkInHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        chkSMS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkSMS.setForeground(new java.awt.Color(0, 102, 153));
        chkSMS.setText("SMS Hóa Đơn");
        pnlThanhToan.add(chkSMS, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, -1, -1));

        lblTongThanhTien.setBackground(new java.awt.Color(51, 51, 51));
        lblTongThanhTien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTongThanhTien.setForeground(new java.awt.Color(0, 102, 153));
        lblTongThanhTien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTongThanhTien.setText("TỔNG THÀNH TIỀN:");
        pnlThanhToan.add(lblTongThanhTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 150, 40));

        txtTongThanhTien.setBackground(new java.awt.Color(51, 51, 51));
        txtTongThanhTien.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        txtTongThanhTien.setForeground(new java.awt.Color(255, 0, 0));
        txtTongThanhTien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTongThanhTien.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlThanhToan.add(txtTongThanhTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 270, 40));

        txtTongTienHD.setBackground(new java.awt.Color(51, 51, 51));
        txtTongTienHD.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtTongTienHD.setForeground(new java.awt.Color(255, 0, 0));
        txtTongTienHD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTongTienHD.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlThanhToan.add(txtTongTienHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 270, 40));

        txtTienKhachDua.setBackground(new java.awt.Color(51, 51, 51));
        txtTienKhachDua.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        txtTienKhachDua.setForeground(new java.awt.Color(0, 0, 204));
        txtTienKhachDua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTienKhachDua.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlThanhToan.add(txtTienKhachDua, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 270, 40));

        pnlRight.add(pnlThanhToan, "thanhToan");

        pnlDichVu.setBackground(new java.awt.Color(51, 51, 51));
        pnlDichVu.setMinimumSize(new java.awt.Dimension(525, 560));
        pnlDichVu.setPreferredSize(new java.awt.Dimension(525, 560));
        pnlDichVu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabbedDV.setBackground(new java.awt.Color(51, 51, 51));
        tabbedDV.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        tabbedDV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tabbedDV.setMaximumSize(new java.awt.Dimension(450, 580));
        tabbedDV.setMinimumSize(new java.awt.Dimension(450, 580));
        tabbedDV.setOpaque(true);
        tabbedDV.setPreferredSize(new java.awt.Dimension(450, 580));
        pnlDichVu.add(tabbedDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        pnlQuickSearch.setBackground(new java.awt.Color(51, 51, 51));
        pnlQuickSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtQuickSearch.setBackground(new java.awt.Color(51, 51, 51));
        txtQuickSearch.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtQuickSearch.setForeground(new java.awt.Color(255, 255, 0));
        txtQuickSearch.setMaximumSize(new java.awt.Dimension(10, 20));
        txtQuickSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQuickSearchKeyReleased(evt);
            }
        });
        pnlQuickSearch.add(txtQuickSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 200, 30));

        lblQuickSearch.setBackground(new java.awt.Color(255, 255, 255));
        lblQuickSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQuickSearch.setForeground(new java.awt.Color(255, 255, 255));
        lblQuickSearch.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblQuickSearch.setText("Tìm kiếm nhanh:");
        lblQuickSearch.setMaximumSize(new java.awt.Dimension(100, 20));
        lblQuickSearch.setPreferredSize(new java.awt.Dimension(100, 20));
        pnlQuickSearch.add(lblQuickSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 130, 30));

        pnlDichVu.add(pnlQuickSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 30));

        pnlRight.add(pnlDichVu, "dichVu");

        pnlRoot.add(pnlRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 500, 690));

        add(pnlRoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 690));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
      
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnTinhTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhTienActionPerformed

     
    }//GEN-LAST:event_btnTinhTienActionPerformed

    private void txtTenKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTenKHMouseClicked
        // TODO add your handling code here:
        txtTenKH.requestFocus();
    }//GEN-LAST:event_txtTenKHMouseClicked

    private void txtSDTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSDTMouseClicked
        // TODO add your handling code here:
        txtSDT.requestFocus();
    }//GEN-LAST:event_txtSDTMouseClicked

    private void btnChuyenPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenPhongActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_btnChuyenPhongActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnHuyActionPerformed

    private void txtQuickSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuickSearchKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtQuickSearchKeyReleased

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
    }//GEN-LAST:event_num4ActionPerformed

    private void num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num0ActionPerformed
    }//GEN-LAST:event_num0ActionPerformed

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num1ActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
    }//GEN-LAST:event_num2ActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
    }//GEN-LAST:event_num3ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
    }//GEN-LAST:event_num5ActionPerformed

    private void num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num6ActionPerformed

    private void num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num7ActionPerformed

    private void num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num8ActionPerformed

    private void num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num9ActionPerformed

    private void txtVoucherKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVoucherKeyReleased
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtVoucherKeyReleased

    private void num10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num10ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_num10ActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
       

    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void pnlThanhToanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThanhToanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlThanhToanMouseClicked

    private void pnlThanhToanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnlThanhToanKeyReleased
       
    }//GEN-LAST:event_pnlThanhToanKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnChuyenPhong;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnTinhTien;
    private javax.swing.JCheckBox chkInHoaDon;
    private javax.swing.JCheckBox chkSMS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblChitiet;
    private javax.swing.JLabel lblDT;
    private javax.swing.JLabel lblGiaPhong;
    private javax.swing.JLabel lblGiovao;
    private javax.swing.JLabel lblKhachhangchuasudung;
    private javax.swing.JLabel lblQuickSearch;
    private javax.swing.JLabel lblStatusVoucher;
    private javax.swing.JLabel lblTenKH;
    private javax.swing.JLabel lblThoiluong;
    private javax.swing.JLabel lblTienDV;
    private javax.swing.JLabel lblTienGio;
    private javax.swing.JLabel lblTienKhachDua;
    private javax.swing.JLabel lblTongTamTinh;
    private javax.swing.JLabel lblTongThanhTien;
    private javax.swing.JLabel lblTongTien1;
    private javax.swing.JLabel lblVoucher;
    private javax.swing.JButton num0;
    private javax.swing.JButton num1;
    private javax.swing.JButton num10;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JPanel pnlChiTietHoaDon;
    private javax.swing.JPanel pnlDichVu;
    private javax.swing.JPanel pnlHoaDon;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlQuickSearch;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JPanel pnlRoot;
    private javax.swing.JPanel pnlThanhToan;
    private javax.swing.JScrollPane scrHoaDon;
    private javax.swing.JTabbedPane tabbedDV;
    private javax.swing.JLabel txtGiaPhong;
    private javax.swing.JLabel txtGioVao;
    private javax.swing.JTextField txtQuickSearch;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JLabel txtTenPhong;
    private javax.swing.JLabel txtTenPhong1;
    private javax.swing.JLabel txtThoiluong;
    private javax.swing.JLabel txtTienDV;
    private javax.swing.JLabel txtTienGio;
    private javax.swing.JLabel txtTienKhachDua;
    private javax.swing.JLabel txtTongTamTinh;
    private javax.swing.JLabel txtTongThanhTien;
    private javax.swing.JLabel txtTongTienHD;
    private javax.swing.JTextField txtVoucher;
    // End of variables declaration//GEN-END:variables
}
