package com.karaoke.ui;

import static com.karaoke.helper.OpenJPanel.openJPanel;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author TVD
 */
public class MainJFrame extends javax.swing.JFrame {

    int count = 0;
    int index = 0;
    List<JLabel> listJLabelsMenu = new ArrayList<JLabel>();
    CardLayout cardLayout = null;

    public MainJFrame() {
        setUndecorated(true);
        initComponents();
        init();
        setLocationRelativeTo(null);
        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
        setEventJLabelsWindows();
        addJLabelsToMenu(lblTrangChinh, lblQuanLy, lblThietLap, lblThongKe, lblTroGiup, lblDangXuat, lblQLDichvu,
                lblQLNCC, lblQLSMS, lblQLNguoidung, lblQLPhong, lblTKHoadon, lblTKKhunggio, lnlTLThongtinquan, lblHDSD, lblTLThoigianmophong, lblTLGiamgia, lblTTTG);
        cardLayout = (CardLayout) pnlLeft.getLayout();
        lblQuayLai.setVisible(false);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoot = new javax.swing.JPanel();
        pnlLeft = new javax.swing.JPanel();
        pnlMenuMain = new javax.swing.JPanel();
        lblTrangChinh = new javax.swing.JLabel();
        lblQuanLy = new javax.swing.JLabel();
        lblThongKe = new javax.swing.JLabel();
        lblThietLap = new javax.swing.JLabel();
        lblTroGiup = new javax.swing.JLabel();
        lblDangXuat = new javax.swing.JLabel();
        pnlMenuQuanLy = new javax.swing.JPanel();
        lblQuanLyTitle = new javax.swing.JLabel();
        lblQLNguoidung = new javax.swing.JLabel();
        lblQLPhong = new javax.swing.JLabel();
        lblQLDichvu = new javax.swing.JLabel();
        lblQLNCC = new javax.swing.JLabel();
        lblQLSMS = new javax.swing.JLabel();
        pnlMenuThongKe = new javax.swing.JPanel();
        lblThongKetTitle = new javax.swing.JLabel();
        lblTKHoadon = new javax.swing.JLabel();
        lblTKKhunggio = new javax.swing.JLabel();
        pnlMenuThietLap = new javax.swing.JPanel();
        lblThietLapTitle = new javax.swing.JLabel();
        lnlTLThongtinquan = new javax.swing.JLabel();
        lblTLThoigianmophong = new javax.swing.JLabel();
        lblTLGiamgia = new javax.swing.JLabel();
        pnlMenuTroGiup = new javax.swing.JPanel();
        lblTroGiupTitle = new javax.swing.JLabel();
        lblHDSD = new javax.swing.JLabel();
        lblTTTG = new javax.swing.JLabel();
        lblQuayLai = new javax.swing.JLabel();
        lblBackgroundMenu = new javax.swing.JLabel();
        pnlView = new javax.swing.JPanel();
        lblLogoLARGE = new javax.swing.JLabel();
        lblSlogan = new javax.swing.JLabel();
        lblBackgroundView = new javax.swing.JLabel();
        pnlFoot = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();
        lblTenKara = new javax.swing.JLabel();
        lblInformationNhanVien = new javax.swing.JLabel();
        lblDiaChiKara = new javax.swing.JLabel();
        pnlTop = new javax.swing.JPanel();
        lblMinimizeWindow = new javax.swing.JLabel();
        lblCloseWindow = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KaraokeManagement - Phần mềm quản lý Phòng Hát Karaoke v1.1");
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRoot.setMaximumSize(new java.awt.Dimension(1366, 768));
        pnlRoot.setMinimumSize(new java.awt.Dimension(1366, 768));
        pnlRoot.setOpaque(false);
        pnlRoot.setPreferredSize(new java.awt.Dimension(1366, 768));
        pnlRoot.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLeft.setBackground(new java.awt.Color(255, 255, 255));
        pnlLeft.setToolTipText("");
        pnlLeft.setMaximumSize(new java.awt.Dimension(310, 640));
        pnlLeft.setMinimumSize(new java.awt.Dimension(310, 640));
        pnlLeft.setOpaque(false);
        pnlLeft.setPreferredSize(new java.awt.Dimension(310, 640));
        pnlLeft.setLayout(new java.awt.CardLayout());

        pnlMenuMain.setBackground(new java.awt.Color(0, 0, 51));
        pnlMenuMain.setForeground(new java.awt.Color(255, 255, 255));
        pnlMenuMain.setToolTipText("");
        pnlMenuMain.setMaximumSize(new java.awt.Dimension(310, 690));
        pnlMenuMain.setMinimumSize(new java.awt.Dimension(310, 690));
        pnlMenuMain.setOpaque(false);
        pnlMenuMain.setPreferredSize(new java.awt.Dimension(310, 690));
        pnlMenuMain.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 20));

        lblTrangChinh.setBackground(new java.awt.Color(255, 255, 255));
        lblTrangChinh.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lblTrangChinh.setForeground(new java.awt.Color(0, 0, 51));
        lblTrangChinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTrangChinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/karaoke/images/icon/icons8_Home_32px_1.png"))); // NOI18N
        lblTrangChinh.setText("PHÒNG HÁT");
        lblTrangChinh.setMaximumSize(new java.awt.Dimension(250, 50));
        lblTrangChinh.setMinimumSize(new java.awt.Dimension(250, 50));
        lblTrangChinh.setOpaque(true);
        lblTrangChinh.setPreferredSize(new java.awt.Dimension(250, 50));
        pnlMenuMain.add(lblTrangChinh);

        lblQuanLy.setBackground(new java.awt.Color(255, 255, 255));
        lblQuanLy.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lblQuanLy.setForeground(new java.awt.Color(0, 0, 51));
        lblQuanLy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuanLy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/karaoke/images/icon/icons8_Staff_32px.png"))); // NOI18N
        lblQuanLy.setText("QUẢN LÝ");
        lblQuanLy.setMaximumSize(new java.awt.Dimension(250, 50));
        lblQuanLy.setMinimumSize(new java.awt.Dimension(250, 50));
        lblQuanLy.setOpaque(true);
        lblQuanLy.setPreferredSize(new java.awt.Dimension(250, 50));
        pnlMenuMain.add(lblQuanLy);

        lblThongKe.setBackground(new java.awt.Color(255, 255, 255));
        lblThongKe.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lblThongKe.setForeground(new java.awt.Color(0, 0, 51));
        lblThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/karaoke/images/icon/icons8_Futures_32px.png"))); // NOI18N
        lblThongKe.setText("THỐNG KÊ");
        lblThongKe.setMaximumSize(new java.awt.Dimension(250, 50));
        lblThongKe.setMinimumSize(new java.awt.Dimension(250, 50));
        lblThongKe.setOpaque(true);
        lblThongKe.setPreferredSize(new java.awt.Dimension(250, 50));
        pnlMenuMain.add(lblThongKe);

        lblThietLap.setBackground(new java.awt.Color(255, 255, 255));
        lblThietLap.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lblThietLap.setForeground(new java.awt.Color(0, 0, 51));
        lblThietLap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThietLap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/karaoke/images/icon/icons8_Automation_32px.png"))); // NOI18N
        lblThietLap.setText("THIẾT LẬP");
        lblThietLap.setMaximumSize(new java.awt.Dimension(250, 50));
        lblThietLap.setMinimumSize(new java.awt.Dimension(250, 50));
        lblThietLap.setOpaque(true);
        lblThietLap.setPreferredSize(new java.awt.Dimension(250, 50));
        pnlMenuMain.add(lblThietLap);

        lblTroGiup.setBackground(new java.awt.Color(255, 255, 255));
        lblTroGiup.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lblTroGiup.setForeground(new java.awt.Color(0, 0, 51));
        lblTroGiup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTroGiup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/karaoke/images/icon/icons8_User_Manual_32px.png"))); // NOI18N
        lblTroGiup.setText("TRỢ GIÚP");
        lblTroGiup.setMaximumSize(new java.awt.Dimension(250, 50));
        lblTroGiup.setMinimumSize(new java.awt.Dimension(250, 50));
        lblTroGiup.setOpaque(true);
        lblTroGiup.setPreferredSize(new java.awt.Dimension(250, 50));
        pnlMenuMain.add(lblTroGiup);

        lblDangXuat.setBackground(new java.awt.Color(255, 255, 255));
        lblDangXuat.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lblDangXuat.setForeground(new java.awt.Color(0, 0, 51));
        lblDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/karaoke/images/icon/icons8_Shutdown_32px.png"))); // NOI18N
        lblDangXuat.setText("ĐĂNG XUẤT");
        lblDangXuat.setMaximumSize(new java.awt.Dimension(250, 50));
        lblDangXuat.setMinimumSize(new java.awt.Dimension(250, 50));
        lblDangXuat.setOpaque(true);
        lblDangXuat.setPreferredSize(new java.awt.Dimension(250, 50));
        pnlMenuMain.add(lblDangXuat);

        pnlLeft.add(pnlMenuMain, "main");

        pnlMenuQuanLy.setBackground(new java.awt.Color(0, 0, 51));
        pnlMenuQuanLy.setForeground(new java.awt.Color(255, 255, 255));
        pnlMenuQuanLy.setToolTipText("");
        pnlMenuQuanLy.setMaximumSize(new java.awt.Dimension(310, 690));
        pnlMenuQuanLy.setMinimumSize(new java.awt.Dimension(310, 690));
        pnlMenuQuanLy.setOpaque(false);
        pnlMenuQuanLy.setPreferredSize(new java.awt.Dimension(310, 690));
        pnlMenuQuanLy.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 20));

        lblQuanLyTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblQuanLyTitle.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lblQuanLyTitle.setForeground(new java.awt.Color(0, 0, 51));
        lblQuanLyTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuanLyTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/karaoke/images/icon/icons8_Staff_32px.png"))); // NOI18N
        lblQuanLyTitle.setText("QUẢN LÝ");
        lblQuanLyTitle.setMaximumSize(new java.awt.Dimension(250, 50));
        lblQuanLyTitle.setMinimumSize(new java.awt.Dimension(250, 50));
        lblQuanLyTitle.setOpaque(true);
        lblQuanLyTitle.setPreferredSize(new java.awt.Dimension(250, 50));
        pnlMenuQuanLy.add(lblQuanLyTitle);

        lblQLNguoidung.setBackground(new java.awt.Color(0, 0, 51));
        lblQLNguoidung.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblQLNguoidung.setForeground(new java.awt.Color(255, 255, 255));
        lblQLNguoidung.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQLNguoidung.setText("QUẢN LÝ NGƯỜI DÙNG");
        lblQLNguoidung.setMaximumSize(new java.awt.Dimension(250, 50));
        lblQLNguoidung.setMinimumSize(new java.awt.Dimension(250, 50));
        lblQLNguoidung.setOpaque(true);
        lblQLNguoidung.setPreferredSize(new java.awt.Dimension(250, 50));
        lblQLNguoidung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLNguoidungMouseClicked(evt);
            }
        });
        pnlMenuQuanLy.add(lblQLNguoidung);

        lblQLPhong.setBackground(new java.awt.Color(0, 0, 51));
        lblQLPhong.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblQLPhong.setForeground(new java.awt.Color(255, 255, 255));
        lblQLPhong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQLPhong.setText("QUẢN LÝ PHÒNG");
        lblQLPhong.setMaximumSize(new java.awt.Dimension(250, 50));
        lblQLPhong.setMinimumSize(new java.awt.Dimension(250, 50));
        lblQLPhong.setOpaque(true);
        lblQLPhong.setPreferredSize(new java.awt.Dimension(250, 50));
        lblQLPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLPhongMouseClicked(evt);
            }
        });
        pnlMenuQuanLy.add(lblQLPhong);

        lblQLDichvu.setBackground(new java.awt.Color(0, 0, 51));
        lblQLDichvu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblQLDichvu.setForeground(new java.awt.Color(255, 255, 255));
        lblQLDichvu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQLDichvu.setText("QUẢN LÝ DỊCH VỤ");
        lblQLDichvu.setMaximumSize(new java.awt.Dimension(250, 50));
        lblQLDichvu.setMinimumSize(new java.awt.Dimension(250, 50));
        lblQLDichvu.setOpaque(true);
        lblQLDichvu.setPreferredSize(new java.awt.Dimension(250, 50));
        lblQLDichvu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLDichvuMouseClicked(evt);
            }
        });
        pnlMenuQuanLy.add(lblQLDichvu);

        lblQLNCC.setBackground(new java.awt.Color(0, 0, 51));
        lblQLNCC.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblQLNCC.setForeground(new java.awt.Color(255, 255, 255));
        lblQLNCC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQLNCC.setText("QUẢN LÝ NHÀ CUNG CẤP");
        lblQLNCC.setMaximumSize(new java.awt.Dimension(250, 50));
        lblQLNCC.setMinimumSize(new java.awt.Dimension(250, 50));
        lblQLNCC.setOpaque(true);
        lblQLNCC.setPreferredSize(new java.awt.Dimension(250, 50));
        lblQLNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLNCCMouseClicked(evt);
            }
        });
        pnlMenuQuanLy.add(lblQLNCC);

        lblQLSMS.setBackground(new java.awt.Color(0, 0, 51));
        lblQLSMS.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblQLSMS.setForeground(new java.awt.Color(255, 255, 255));
        lblQLSMS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQLSMS.setText("SMS MARKETING");
        lblQLSMS.setMaximumSize(new java.awt.Dimension(250, 50));
        lblQLSMS.setMinimumSize(new java.awt.Dimension(250, 50));
        lblQLSMS.setOpaque(true);
        lblQLSMS.setPreferredSize(new java.awt.Dimension(250, 50));
        lblQLSMS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLSMSMouseClicked(evt);
            }
        });
        pnlMenuQuanLy.add(lblQLSMS);

        pnlLeft.add(pnlMenuQuanLy, "quanly");

        pnlMenuThongKe.setBackground(new java.awt.Color(0, 0, 51));
        pnlMenuThongKe.setForeground(new java.awt.Color(255, 255, 255));
        pnlMenuThongKe.setToolTipText("");
        pnlMenuThongKe.setMaximumSize(new java.awt.Dimension(310, 690));
        pnlMenuThongKe.setMinimumSize(new java.awt.Dimension(310, 690));
        pnlMenuThongKe.setOpaque(false);
        pnlMenuThongKe.setPreferredSize(new java.awt.Dimension(310, 690));
        pnlMenuThongKe.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 20));

        lblThongKetTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblThongKetTitle.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lblThongKetTitle.setForeground(new java.awt.Color(0, 0, 51));
        lblThongKetTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThongKetTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/karaoke/images/icon/icons8_Futures_32px.png"))); // NOI18N
        lblThongKetTitle.setText("THỐNG KÊ");
        lblThongKetTitle.setMaximumSize(new java.awt.Dimension(250, 50));
        lblThongKetTitle.setMinimumSize(new java.awt.Dimension(250, 50));
        lblThongKetTitle.setOpaque(true);
        lblThongKetTitle.setPreferredSize(new java.awt.Dimension(250, 50));
        pnlMenuThongKe.add(lblThongKetTitle);

        lblTKHoadon.setBackground(new java.awt.Color(0, 0, 51));
        lblTKHoadon.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTKHoadon.setForeground(new java.awt.Color(255, 255, 255));
        lblTKHoadon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTKHoadon.setText("THỐNG KÊ HÓA ĐƠN");
        lblTKHoadon.setMaximumSize(new java.awt.Dimension(250, 50));
        lblTKHoadon.setMinimumSize(new java.awt.Dimension(250, 50));
        lblTKHoadon.setOpaque(true);
        lblTKHoadon.setPreferredSize(new java.awt.Dimension(250, 50));
        lblTKHoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTKHoadonMouseClicked(evt);
            }
        });
        pnlMenuThongKe.add(lblTKHoadon);

        lblTKKhunggio.setBackground(new java.awt.Color(0, 0, 51));
        lblTKKhunggio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTKKhunggio.setForeground(new java.awt.Color(255, 255, 255));
        lblTKKhunggio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTKKhunggio.setText("THỐNG KÊ KHUNG GIỜ");
        lblTKKhunggio.setMaximumSize(new java.awt.Dimension(250, 50));
        lblTKKhunggio.setMinimumSize(new java.awt.Dimension(250, 50));
        lblTKKhunggio.setOpaque(true);
        lblTKKhunggio.setPreferredSize(new java.awt.Dimension(250, 50));
        lblTKKhunggio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTKKhunggioMouseClicked(evt);
            }
        });
        pnlMenuThongKe.add(lblTKKhunggio);

        pnlLeft.add(pnlMenuThongKe, "thongke");

        pnlMenuThietLap.setBackground(new java.awt.Color(0, 0, 51));
        pnlMenuThietLap.setForeground(new java.awt.Color(255, 255, 255));
        pnlMenuThietLap.setToolTipText("");
        pnlMenuThietLap.setMaximumSize(new java.awt.Dimension(310, 690));
        pnlMenuThietLap.setMinimumSize(new java.awt.Dimension(310, 690));
        pnlMenuThietLap.setOpaque(false);
        pnlMenuThietLap.setPreferredSize(new java.awt.Dimension(310, 690));
        pnlMenuThietLap.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 20));

        lblThietLapTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblThietLapTitle.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lblThietLapTitle.setForeground(new java.awt.Color(0, 0, 51));
        lblThietLapTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThietLapTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/karaoke/images/icon/icons8_Automation_32px.png"))); // NOI18N
        lblThietLapTitle.setText("THIẾT LẬP");
        lblThietLapTitle.setMaximumSize(new java.awt.Dimension(250, 50));
        lblThietLapTitle.setMinimumSize(new java.awt.Dimension(250, 50));
        lblThietLapTitle.setOpaque(true);
        lblThietLapTitle.setPreferredSize(new java.awt.Dimension(250, 50));
        pnlMenuThietLap.add(lblThietLapTitle);

        lnlTLThongtinquan.setBackground(new java.awt.Color(0, 0, 51));
        lnlTLThongtinquan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lnlTLThongtinquan.setForeground(new java.awt.Color(255, 255, 255));
        lnlTLThongtinquan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnlTLThongtinquan.setText("THIẾT LẬP THÔNG TIN QUÁN");
        lnlTLThongtinquan.setMaximumSize(new java.awt.Dimension(250, 50));
        lnlTLThongtinquan.setMinimumSize(new java.awt.Dimension(250, 50));
        lnlTLThongtinquan.setOpaque(true);
        lnlTLThongtinquan.setPreferredSize(new java.awt.Dimension(250, 50));
        lnlTLThongtinquan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lnlTLThongtinquanMouseClicked(evt);
            }
        });
        pnlMenuThietLap.add(lnlTLThongtinquan);

        lblTLThoigianmophong.setBackground(new java.awt.Color(0, 0, 51));
        lblTLThoigianmophong.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTLThoigianmophong.setForeground(new java.awt.Color(255, 255, 255));
        lblTLThoigianmophong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTLThoigianmophong.setText("THIẾT LẬP THỜI GIAN MỞ PHÒNG");
        lblTLThoigianmophong.setMaximumSize(new java.awt.Dimension(250, 50));
        lblTLThoigianmophong.setMinimumSize(new java.awt.Dimension(250, 50));
        lblTLThoigianmophong.setOpaque(true);
        lblTLThoigianmophong.setPreferredSize(new java.awt.Dimension(250, 50));
        lblTLThoigianmophong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTLThoigianmophongMouseClicked(evt);
            }
        });
        pnlMenuThietLap.add(lblTLThoigianmophong);

        lblTLGiamgia.setBackground(new java.awt.Color(0, 0, 51));
        lblTLGiamgia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTLGiamgia.setForeground(new java.awt.Color(255, 255, 255));
        lblTLGiamgia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTLGiamgia.setText("THIẾT LẬP GIẢM GIÁ");
        lblTLGiamgia.setMaximumSize(new java.awt.Dimension(250, 50));
        lblTLGiamgia.setMinimumSize(new java.awt.Dimension(250, 50));
        lblTLGiamgia.setOpaque(true);
        lblTLGiamgia.setPreferredSize(new java.awt.Dimension(250, 50));
        lblTLGiamgia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTLGiamgiaMouseClicked(evt);
            }
        });
        pnlMenuThietLap.add(lblTLGiamgia);

        pnlLeft.add(pnlMenuThietLap, "thietlap");

        pnlMenuTroGiup.setBackground(new java.awt.Color(0, 0, 51));
        pnlMenuTroGiup.setForeground(new java.awt.Color(255, 255, 255));
        pnlMenuTroGiup.setToolTipText("");
        pnlMenuTroGiup.setMaximumSize(new java.awt.Dimension(310, 690));
        pnlMenuTroGiup.setMinimumSize(new java.awt.Dimension(310, 690));
        pnlMenuTroGiup.setOpaque(false);
        pnlMenuTroGiup.setPreferredSize(new java.awt.Dimension(310, 690));
        pnlMenuTroGiup.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 20));

        lblTroGiupTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTroGiupTitle.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lblTroGiupTitle.setForeground(new java.awt.Color(0, 0, 51));
        lblTroGiupTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTroGiupTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/karaoke/images/icon/icons8_User_Manual_32px.png"))); // NOI18N
        lblTroGiupTitle.setText("TRỢ GIÚP");
        lblTroGiupTitle.setMaximumSize(new java.awt.Dimension(250, 50));
        lblTroGiupTitle.setMinimumSize(new java.awt.Dimension(250, 50));
        lblTroGiupTitle.setOpaque(true);
        lblTroGiupTitle.setPreferredSize(new java.awt.Dimension(250, 50));
        pnlMenuTroGiup.add(lblTroGiupTitle);

        lblHDSD.setBackground(new java.awt.Color(0, 0, 51));
        lblHDSD.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblHDSD.setForeground(new java.awt.Color(255, 255, 255));
        lblHDSD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHDSD.setText("HƯỚNG DẪN SỬ DỤNG");
        lblHDSD.setMaximumSize(new java.awt.Dimension(250, 50));
        lblHDSD.setMinimumSize(new java.awt.Dimension(250, 50));
        lblHDSD.setOpaque(true);
        lblHDSD.setPreferredSize(new java.awt.Dimension(250, 50));
        lblHDSD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHDSDMouseClicked(evt);
            }
        });
        pnlMenuTroGiup.add(lblHDSD);

        lblTTTG.setBackground(new java.awt.Color(0, 0, 51));
        lblTTTG.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTTTG.setForeground(new java.awt.Color(255, 255, 255));
        lblTTTG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTTTG.setText("THÔNG TIN TÁC GIẢ");
        lblTTTG.setMaximumSize(new java.awt.Dimension(250, 50));
        lblTTTG.setMinimumSize(new java.awt.Dimension(250, 50));
        lblTTTG.setOpaque(true);
        lblTTTG.setPreferredSize(new java.awt.Dimension(250, 50));
        lblTTTG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTTTGMouseClicked(evt);
            }
        });
        pnlMenuTroGiup.add(lblTTTG);

        pnlLeft.add(pnlMenuTroGiup, "trogiup");

        pnlRoot.add(pnlLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, 460));

        lblQuayLai.setBackground(new java.awt.Color(0, 0, 51));
        lblQuayLai.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblQuayLai.setForeground(new java.awt.Color(255, 255, 255));
        lblQuayLai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/karaoke/images/icon/icons8_Go_Back_32px.png"))); // NOI18N
        lblQuayLai.setText("QUAY LẠI");
        lblQuayLai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblQuayLai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuayLaiMouseClicked(evt);
            }
        });
        pnlRoot.add(lblQuayLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, 140, 30));

        lblBackgroundMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/karaoke/images/icon/background.png"))); // NOI18N
        pnlRoot.add(lblBackgroundMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 690));

        pnlView.setMaximumSize(new java.awt.Dimension(1050, 690));
        pnlView.setMinimumSize(new java.awt.Dimension(1050, 690));
        pnlView.setOpaque(false);
        pnlView.setPreferredSize(new java.awt.Dimension(1050, 690));
        pnlView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogoLARGE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogoLARGE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/karaoke/images/icon/Karaoke_LogoLARGE.png"))); // NOI18N
        pnlView.add(lblLogoLARGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1060, 330));

        lblSlogan.setBackground(new java.awt.Color(255, 255, 255));
        lblSlogan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSlogan.setForeground(new java.awt.Color(153, 204, 255));
        lblSlogan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSlogan.setText("Phần mềm Quản lý Phòng hát Karaoke theo phong cách chuyên nghiệp");
        pnlView.add(lblSlogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 410, 1050, 40));

        pnlRoot.add(pnlView, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, -1));

        lblBackgroundView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/karaoke/images/icon/background_room.jpg"))); // NOI18N
        lblBackgroundView.setText("jLabel1");
        lblBackgroundView.setMaximumSize(new java.awt.Dimension(1056, 650));
        lblBackgroundView.setMinimumSize(new java.awt.Dimension(1056, 650));
        lblBackgroundView.setName(""); // NOI18N
        lblBackgroundView.setPreferredSize(new java.awt.Dimension(1056, 650));
        pnlRoot.add(lblBackgroundView, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 1060, 690));

        pnlFoot.setBackground(new java.awt.Color(30, 30, 30));
        pnlFoot.setPreferredSize(new java.awt.Dimension(1366, 700));
        pnlFoot.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTime.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        lblTime.setMaximumSize(new java.awt.Dimension(270, 60));
        lblTime.setMinimumSize(new java.awt.Dimension(270, 60));
        lblTime.setPreferredSize(new java.awt.Dimension(270, 60));
        pnlFoot.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, -10, 230, 70));

        lblTenKara.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblTenKara.setForeground(new java.awt.Color(255, 255, 0));
        lblTenKara.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTenKara.setText("KARAOKE TÌNH THƠ");
        lblTenKara.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlFoot.add(lblTenKara, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 30));

        lblInformationNhanVien.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        lblInformationNhanVien.setForeground(new java.awt.Color(0, 102, 153));
        lblInformationNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblInformationNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/karaoke/images/icon/user.png"))); // NOI18N
        lblInformationNhanVien.setText("<html>Tên người dùng: <font color = WHITE><b> KASIM HOÀNG VŨ </b></font><br>Vai trò: <font color = WHITE><b>Admin </font></b></html>");
        lblInformationNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        lblInformationNhanVien.setMaximumSize(new java.awt.Dimension(270, 60));
        lblInformationNhanVien.setMinimumSize(new java.awt.Dimension(270, 60));
        lblInformationNhanVien.setPreferredSize(new java.awt.Dimension(270, 60));
        pnlFoot.add(lblInformationNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 50));

        lblDiaChiKara.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDiaChiKara.setForeground(new java.awt.Color(255, 255, 255));
        lblDiaChiKara.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDiaChiKara.setText("391A Nam Kỳ Khởi Nghĩa, P.14, Q.3, TP. Hồ Chí Minh - ĐT: 028 2821 2822");
        lblDiaChiKara.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlFoot.add(lblDiaChiKara, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1370, 20));

        pnlRoot.add(pnlFoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, -1, 50));

        getContentPane().add(pnlRoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 28, -1, 740));

        pnlTop.setBackground(new java.awt.Color(0, 0, 0));
        pnlTop.setMaximumSize(new java.awt.Dimension(1366, 30));
        pnlTop.setMinimumSize(new java.awt.Dimension(1366, 30));
        pnlTop.setPreferredSize(new java.awt.Dimension(1366, 30));
        pnlTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMinimizeWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/karaoke/images/icon/minimize_window.png"))); // NOI18N
        lblMinimizeWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlTop.add(lblMinimizeWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 0, 30, 20));

        lblCloseWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/karaoke/images/icon/close_window.png"))); // NOI18N
        lblCloseWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlTop.add(lblCloseWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(1335, 0, 30, 20));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html><font color = YELLOW>KARAOKE MANAGEMENT v1.1</font> - Phần mềm Quản Lý Phòng Hát Karaoke");
        pnlTop.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 1300, 20));

        getContentPane().add(pnlTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblQuayLaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuayLaiMouseClicked
        // TODO add your handling code here:
        cardLayout.show(pnlLeft, "main");
        lblQuayLai.setVisible(false);
    }//GEN-LAST:event_lblQuayLaiMouseClicked

    private void lblQLNguoidungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLNguoidungMouseClicked
        // TODO add your handling code here:
        openJPanel(pnlView, new QLNguoiDung2());

    }//GEN-LAST:event_lblQLNguoidungMouseClicked

    private void lblQLPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLPhongMouseClicked
        // TODO add your handling code here:
        openJPanel(pnlView, new QLPhongJPanel());

    }//GEN-LAST:event_lblQLPhongMouseClicked

    private void lblQLDichvuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLDichvuMouseClicked
        // TODO add your handling code here:
        openJPanel(pnlView, new QLDichVuJPanel());
    }//GEN-LAST:event_lblQLDichvuMouseClicked

    private void lblQLNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLNCCMouseClicked
        // TODO add your handling code here:
        openJPanel(pnlView, new QLNhaCungCapJPanel());

    }//GEN-LAST:event_lblQLNCCMouseClicked

    private void lblQLSMSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLSMSMouseClicked
        // TODO add your handling code here:
        //openJPanel(pnlView, new QLSMSJPanel());

    }//GEN-LAST:event_lblQLSMSMouseClicked

    private void lblTKHoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTKHoadonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTKHoadonMouseClicked

    private void lblTKKhunggioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTKKhunggioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTKKhunggioMouseClicked

    private void lnlTLThongtinquanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lnlTLThongtinquanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lnlTLThongtinquanMouseClicked

    private void lblTLThoigianmophongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTLThoigianmophongMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTLThoigianmophongMouseClicked

    private void lblTLGiamgiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTLGiamgiaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTLGiamgiaMouseClicked

    private void lblHDSDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHDSDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblHDSDMouseClicked

    private void lblTTTGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTTTGMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTTTGMouseClicked
    private void init() {
        new Timer(1000, new ActionListener() {
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy - h:mm:ss a");

            @Override
            public void actionPerformed(ActionEvent e) {
                lblTime.setText("<html>" + format.format(new Date()).replaceAll("-", "<font color = yellow>"));

            }
        }).start();
    }

    private void addJLabelsToMenu(JLabel... lb) { //Hàm xử lý các JLabel Menu (thêm vào list --> bắt sự kiện, hiệu ứng khi rê, click chuột
        for (int i = 0; i < lb.length; i++) {
            listJLabelsMenu.add(lb[i]);
        }
        for (JLabel lbl : listJLabelsMenu) {
            lbl.setBackground(new Color(0, 0, 255, 50));
            lbl.setForeground(Color.WHITE);
            lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            lbl.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    isJLabelActive(lbl);
                    pnlMenuMain.repaint();
                    pnlMenuMain.revalidate();
                    pnlLeft.repaint();
                    pnlLeft.revalidate();
                }

            });
        }
    }

    private void isJLabelActive(JLabel label) {
        for (JLabel lbl : listJLabelsMenu) {
            if (lbl == label) {
                lbl.setForeground(Color.BLACK);
                lbl.setBackground(new Color(255, 255, 255));
                String lblName = label.getText();
                switch (lblName) {
                    case "PHÒNG HÁT":
                        openJPanel(pnlView, new RoomJPanel());
                        break;
                    case "QUẢN LÝ":
                        cardLayout.show(pnlLeft, "quanly");
                        lblQuayLai.setVisible(true);
                        break;
                    case "THỐNG KÊ":
                        cardLayout.show(pnlLeft, "thongke");
                        lblQuayLai.setVisible(true);
                        break;
                    case "THIẾT LẬP":
                        cardLayout.show(pnlLeft, "thietlap");
                        lblQuayLai.setVisible(true);
                        break;
                    case "TRỢ GIÚP":
                        cardLayout.show(pnlLeft, "trogiup");
                        lblQuayLai.setVisible(true);
                        break;

                }
            } else {
                lbl.setForeground(Color.WHITE);
                lbl.setBackground(new Color(0, 0, 255, 50));
            }
        }
    }

    private void setEventJLabelsWindows() {//Hàm set Event cho JLabel Close, Minimize Window
        lblCloseWindow.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                System.exit(0);
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                lblCloseWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/karaoke/images/icon/close_window_entered.png")));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                lblCloseWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/karaoke/images/icon/close_window.png")));

            }
        });

        lblMinimizeWindow.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                setExtendedState(JFrame.ICONIFIED);
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                lblMinimizeWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/karaoke/images/icon/minimize_window_entered.png")));

            }

            @Override
            public void mouseExited(MouseEvent e) {
                lblMinimizeWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/karaoke/images/icon/minimize_window.png")));

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBackgroundMenu;
    private javax.swing.JLabel lblBackgroundView;
    private javax.swing.JLabel lblCloseWindow;
    private javax.swing.JLabel lblDangXuat;
    private javax.swing.JLabel lblDiaChiKara;
    private javax.swing.JLabel lblHDSD;
    private javax.swing.JLabel lblInformationNhanVien;
    private javax.swing.JLabel lblLogoLARGE;
    private javax.swing.JLabel lblMinimizeWindow;
    private javax.swing.JLabel lblQLDichvu;
    private javax.swing.JLabel lblQLNCC;
    private javax.swing.JLabel lblQLNguoidung;
    private javax.swing.JLabel lblQLPhong;
    private javax.swing.JLabel lblQLSMS;
    private javax.swing.JLabel lblQuanLy;
    private javax.swing.JLabel lblQuanLyTitle;
    private javax.swing.JLabel lblQuayLai;
    private javax.swing.JLabel lblSlogan;
    private javax.swing.JLabel lblTKHoadon;
    private javax.swing.JLabel lblTKKhunggio;
    private javax.swing.JLabel lblTLGiamgia;
    private javax.swing.JLabel lblTLThoigianmophong;
    private javax.swing.JLabel lblTTTG;
    private javax.swing.JLabel lblTenKara;
    private javax.swing.JLabel lblThietLap;
    private javax.swing.JLabel lblThietLapTitle;
    private javax.swing.JLabel lblThongKe;
    private javax.swing.JLabel lblThongKetTitle;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTrangChinh;
    private javax.swing.JLabel lblTroGiup;
    private javax.swing.JLabel lblTroGiupTitle;
    private javax.swing.JLabel lnlTLThongtinquan;
    private javax.swing.JPanel pnlFoot;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlMenuMain;
    private javax.swing.JPanel pnlMenuQuanLy;
    private javax.swing.JPanel pnlMenuThietLap;
    private javax.swing.JPanel pnlMenuThongKe;
    private javax.swing.JPanel pnlMenuTroGiup;
    private javax.swing.JPanel pnlRoot;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JPanel pnlView;
    // End of variables declaration//GEN-END:variables
}
