package com.karaoke.ui;

import java.awt.Color;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import javax.swing.Icon;

/**
 *
 * @author TVD
 */
public class QLDichVuJPanel extends javax.swing.JPanel {

    Color roomColor = null;
    Icon roomIcon = null;
    final ScheduledExecutorService svc = Executors.newScheduledThreadPool(1);

    public QLDichVuJPanel() {
        initComponents();
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoot = new javax.swing.JPanel();
        tabbed = new javax.swing.JTabbedPane();
        tabDichVu = new javax.swing.JPanel();
        scrTable = new javax.swing.JScrollPane();
        tblDichvu = new javax.swing.JTable();
        pnlThongtinDV = new javax.swing.JPanel();
        chkCoSan = new javax.swing.JCheckBox();
        lblMaDV = new javax.swing.JLabel();
        txtMaDV = new javax.swing.JTextField();
        lblLoaiDV = new javax.swing.JLabel();
        cboLoai = new javax.swing.JComboBox<>();
        lblHinh = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        lblGiaBan = new javax.swing.JLabel();
        lblHinhmota = new javax.swing.JLabel();
        btnBrowse = new javax.swing.JButton();
        lblTenDV = new javax.swing.JLabel();
        txtTenDV = new javax.swing.JTextField();
        btnThemDV = new javax.swing.JButton();
        btnXoaDV = new javax.swing.JButton();
        btnNewDV = new javax.swing.JButton();
        tabLoaiDV = new javax.swing.JPanel();
        scrTable1 = new javax.swing.JScrollPane();
        tblDSDV = new javax.swing.JTable();
        pnlThongtinLoaiDV = new javax.swing.JPanel();
        txtTenLoaiDV = new javax.swing.JTextField();
        lblTenLoaiDV = new javax.swing.JLabel();
        lblMaLoaiDV = new javax.swing.JLabel();
        txtMaLoaiDV = new javax.swing.JTextField();
        btnThemLOAI = new javax.swing.JButton();
        btnXoaLOAI = new javax.swing.JButton();
        btnNEWLoai = new javax.swing.JButton();
        scrTable2 = new javax.swing.JScrollPane();
        tblLoaiDV = new javax.swing.JTable();
        tabPNH = new javax.swing.JPanel();
        scrTable3 = new javax.swing.JScrollPane();
        tblChiTietPN = new javax.swing.JTable();
        pnlThongtinPhieuNhap = new javax.swing.JPanel();
        lblNhaCungCap = new javax.swing.JLabel();
        lblMaPhieuNhap = new javax.swing.JLabel();
        txtMaPhieuNhap = new javax.swing.JTextField();
        lblNhaCungCap2 = new javax.swing.JLabel();
        cboNhaCungCap = new javax.swing.JComboBox<>();
        txtNgayNhap = new com.toedter.calendar.JDateChooser();
        btnThemPhieuNhap = new javax.swing.JButton();
        btnXoaPhieuNhap = new javax.swing.JButton();
        btnNEWPhieuNhap = new javax.swing.JButton();
        scrTable4 = new javax.swing.JScrollPane();
        tblPhieuNhap = new javax.swing.JTable();
        pnlThongtinChiTietPNH = new javax.swing.JPanel();
        lblNhaCungCap3 = new javax.swing.JLabel();
        lblMaChiTietPN = new javax.swing.JLabel();
        txtMaChiTietPN = new javax.swing.JTextField();
        lblSoLuong = new javax.swing.JLabel();
        cboDichVu = new javax.swing.JComboBox<>();
        txtDonGia = new javax.swing.JTextField();
        lblDonGia = new javax.swing.JLabel();
        spnSoLuong = new javax.swing.JSpinner();
        lblThanhTien = new javax.swing.JLabel();
        txtThanhTien = new javax.swing.JTextField();
        cboLoaiDV = new javax.swing.JComboBox<>();
        btnNEWCTPN = new javax.swing.JButton();
        btnThemCTPN = new javax.swing.JButton();
        btnXoaCTPN = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1050, 690));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1050, 690));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRoot.setBackground(new java.awt.Color(255, 255, 255));
        pnlRoot.setMaximumSize(new java.awt.Dimension(1050, 690));
        pnlRoot.setMinimumSize(new java.awt.Dimension(1050, 690));
        pnlRoot.setOpaque(false);
        pnlRoot.setPreferredSize(new java.awt.Dimension(1050, 690));
        pnlRoot.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabbed.setBackground(new java.awt.Color(255, 255, 255));
        tabbed.setMaximumSize(new java.awt.Dimension(1200, 590));
        tabbed.setMinimumSize(new java.awt.Dimension(1200, 590));
        tabbed.setOpaque(true);
        tabbed.setPreferredSize(new java.awt.Dimension(1200, 590));

        tabDichVu.setBackground(new java.awt.Color(204, 204, 255));
        tabDichVu.setMaximumSize(new java.awt.Dimension(1200, 590));
        tabDichVu.setMinimumSize(new java.awt.Dimension(1200, 590));
        tabDichVu.setPreferredSize(new java.awt.Dimension(1200, 590));
        tabDichVu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDichvu.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        tblDichvu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã DV", "Tên DV", "Loại DV", "Giá bán", "Tồn kho", "Hình"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDichvu.setGridColor(new java.awt.Color(255, 255, 255));
        tblDichvu.setRowHeight(30);
        tblDichvu.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tblDichvu.setSelectionForeground(new java.awt.Color(0, 0, 204));
        tblDichvu.setShowHorizontalLines(false);
        tblDichvu.setShowVerticalLines(false);
        tblDichvu.getTableHeader().setReorderingAllowed(false);
        scrTable.setViewportView(tblDichvu);

        tabDichVu.add(scrTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 41, 600, 410));

        pnlThongtinDV.setBackground(new java.awt.Color(204, 204, 255));
        pnlThongtinDV.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin Dịch vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 3, 14))); // NOI18N
        pnlThongtinDV.setForeground(new java.awt.Color(204, 255, 255));
        pnlThongtinDV.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chkCoSan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chkCoSan.setText("Có sẵn");
        pnlThongtinDV.add(chkCoSan, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 70, 30));

        lblMaDV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMaDV.setText("Mã Dịch vụ");
        pnlThongtinDV.add(lblMaDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 30));

        txtMaDV.setEditable(false);
        txtMaDV.setBackground(new java.awt.Color(255, 255, 255));
        txtMaDV.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtMaDV.setForeground(new java.awt.Color(102, 0, 0));
        pnlThongtinDV.add(txtMaDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 90, 30));

        lblLoaiDV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLoaiDV.setText("Loại Dịch vụ");
        pnlThongtinDV.add(lblLoaiDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 30));

        cboLoai.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        pnlThongtinDV.add(cboLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 190, 30));

        lblHinh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblHinh.setMaximumSize(new java.awt.Dimension(120, 120));
        lblHinh.setMinimumSize(new java.awt.Dimension(120, 120));
        lblHinh.setPreferredSize(new java.awt.Dimension(120, 120));
        pnlThongtinDV.add(lblHinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 120, 120));

        txtGiaBan.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtGiaBan.setForeground(new java.awt.Color(102, 0, 0));
        pnlThongtinDV.add(txtGiaBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 290, 30));

        lblGiaBan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGiaBan.setText("Giá bán");
        pnlThongtinDV.add(lblGiaBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 30));

        lblHinhmota.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHinhmota.setText("Hình ảnh");
        pnlThongtinDV.add(lblHinhmota, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 30));

        btnBrowse.setText("Chọn");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });
        pnlThongtinDV.add(btnBrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 70, -1));

        lblTenDV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTenDV.setText("Tên Dịch vụ");
        pnlThongtinDV.add(lblTenDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));

        txtTenDV.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtTenDV.setForeground(new java.awt.Color(102, 0, 0));
        pnlThongtinDV.add(txtTenDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 290, 30));

        tabDichVu.add(pnlThongtinDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 410, 330));

        btnThemDV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThemDV.setText("Thêm");
        btnThemDV.setMaximumSize(new java.awt.Dimension(130, 50));
        btnThemDV.setMinimumSize(new java.awt.Dimension(130, 50));
        btnThemDV.setPreferredSize(new java.awt.Dimension(130, 50));
        btnThemDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDVActionPerformed(evt);
            }
        });
        tabDichVu.add(btnThemDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, 130, 40));

        btnXoaDV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoaDV.setText("Xóa");
        btnXoaDV.setMaximumSize(new java.awt.Dimension(130, 50));
        btnXoaDV.setMinimumSize(new java.awt.Dimension(130, 50));
        btnXoaDV.setPreferredSize(new java.awt.Dimension(130, 50));
        btnXoaDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaDVActionPerformed(evt);
            }
        });
        tabDichVu.add(btnXoaDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 400, 130, 40));

        btnNewDV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNewDV.setText("Nhập mới");
        btnNewDV.setMaximumSize(new java.awt.Dimension(130, 50));
        btnNewDV.setMinimumSize(new java.awt.Dimension(130, 50));
        btnNewDV.setPreferredSize(new java.awt.Dimension(130, 50));
        btnNewDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewDVActionPerformed(evt);
            }
        });
        tabDichVu.add(btnNewDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 130, 40));

        tabbed.addTab("Dịch vụ", tabDichVu);

        tabLoaiDV.setBackground(new java.awt.Color(204, 204, 255));
        tabLoaiDV.setMaximumSize(new java.awt.Dimension(1200, 590));
        tabLoaiDV.setMinimumSize(new java.awt.Dimension(1200, 590));
        tabLoaiDV.setPreferredSize(new java.awt.Dimension(1200, 590));
        tabLoaiDV.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDSDV.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        tblDSDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Dịch vụ", "Tên Dịch vụ", "Loại Dịch vụ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDSDV.setGridColor(new java.awt.Color(255, 255, 255));
        tblDSDV.setRowHeight(50);
        tblDSDV.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tblDSDV.setSelectionForeground(new java.awt.Color(0, 0, 204));
        tblDSDV.setShowHorizontalLines(false);
        tblDSDV.setShowVerticalLines(false);
        tblDSDV.getTableHeader().setReorderingAllowed(false);
        tblDSDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSDVMouseClicked(evt);
            }
        });
        scrTable1.setViewportView(tblDSDV);

        tabLoaiDV.add(scrTable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 640, 210));

        pnlThongtinLoaiDV.setBackground(new java.awt.Color(204, 204, 255));
        pnlThongtinLoaiDV.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin Loại Dịch vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 3, 14))); // NOI18N
        pnlThongtinLoaiDV.setForeground(new java.awt.Color(204, 255, 255));
        pnlThongtinLoaiDV.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTenLoaiDV.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtTenLoaiDV.setForeground(new java.awt.Color(102, 0, 0));
        pnlThongtinLoaiDV.add(txtTenLoaiDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 260, 30));

        lblTenLoaiDV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTenLoaiDV.setText("Tên Loại Dịch vụ");
        pnlThongtinLoaiDV.add(lblTenLoaiDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, 30));

        lblMaLoaiDV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMaLoaiDV.setText("Mã Loại Dịch vụ");
        pnlThongtinLoaiDV.add(lblMaLoaiDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 110, 30));

        txtMaLoaiDV.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtMaLoaiDV.setForeground(new java.awt.Color(102, 0, 0));
        pnlThongtinLoaiDV.add(txtMaLoaiDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 260, 30));

        tabLoaiDV.add(pnlThongtinLoaiDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 500, 150));

        btnThemLOAI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThemLOAI.setText("Thêm");
        btnThemLOAI.setMaximumSize(new java.awt.Dimension(130, 50));
        btnThemLOAI.setMinimumSize(new java.awt.Dimension(130, 50));
        btnThemLOAI.setPreferredSize(new java.awt.Dimension(130, 50));
        btnThemLOAI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemLOAIActionPerformed(evt);
            }
        });
        tabLoaiDV.add(btnThemLOAI, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 200, 160, -1));

        btnXoaLOAI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoaLOAI.setText("Xóa");
        btnXoaLOAI.setMaximumSize(new java.awt.Dimension(130, 50));
        btnXoaLOAI.setMinimumSize(new java.awt.Dimension(130, 50));
        btnXoaLOAI.setPreferredSize(new java.awt.Dimension(130, 50));
        btnXoaLOAI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaLOAIActionPerformed(evt);
            }
        });
        tabLoaiDV.add(btnXoaLOAI, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 200, 160, -1));

        btnNEWLoai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNEWLoai.setText("Nhập mới");
        btnNEWLoai.setMaximumSize(new java.awt.Dimension(130, 50));
        btnNEWLoai.setMinimumSize(new java.awt.Dimension(130, 50));
        btnNEWLoai.setPreferredSize(new java.awt.Dimension(130, 50));
        btnNEWLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNEWLoaiActionPerformed(evt);
            }
        });
        tabLoaiDV.add(btnNEWLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 160, -1));

        tblLoaiDV.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        tblLoaiDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Loại Dịch vụ", "Tên Loại Dịch vụ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLoaiDV.setGridColor(new java.awt.Color(255, 255, 255));
        tblLoaiDV.setRowHeight(30);
        tblLoaiDV.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tblLoaiDV.setSelectionForeground(new java.awt.Color(0, 0, 204));
        tblLoaiDV.setShowHorizontalLines(false);
        tblLoaiDV.setShowVerticalLines(false);
        tblLoaiDV.getTableHeader().setReorderingAllowed(false);
        tblLoaiDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoaiDVMouseClicked(evt);
            }
        });
        scrTable2.setViewportView(tblLoaiDV);

        tabLoaiDV.add(scrTable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 41, 640, 210));

        tabbed.addTab("Loại Dịch vụ", tabLoaiDV);

        tabPNH.setBackground(new java.awt.Color(204, 204, 255));
        tabPNH.setMaximumSize(new java.awt.Dimension(1200, 590));
        tabPNH.setMinimumSize(new java.awt.Dimension(1200, 590));
        tabPNH.setPreferredSize(new java.awt.Dimension(1200, 590));
        tabPNH.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblChiTietPN.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        tblChiTietPN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Chi tiết PN", "Tên Dịch vụ", "Đơn giá nhập", "Số lượng", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblChiTietPN.setGridColor(new java.awt.Color(255, 255, 255));
        tblChiTietPN.setRowHeight(30);
        tblChiTietPN.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tblChiTietPN.setSelectionForeground(new java.awt.Color(0, 0, 204));
        tblChiTietPN.setShowHorizontalLines(false);
        tblChiTietPN.setShowVerticalLines(false);
        tblChiTietPN.getTableHeader().setReorderingAllowed(false);
        tblChiTietPN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChiTietPNMouseClicked(evt);
            }
        });
        scrTable3.setViewportView(tblChiTietPN);

        tabPNH.add(scrTable3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 640, 210));

        pnlThongtinPhieuNhap.setBackground(new java.awt.Color(204, 204, 255));
        pnlThongtinPhieuNhap.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin Phiếu nhập hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 3, 14))); // NOI18N
        pnlThongtinPhieuNhap.setForeground(new java.awt.Color(204, 255, 255));
        pnlThongtinPhieuNhap.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNhaCungCap.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNhaCungCap.setText("Nhà Cung cấp");
        pnlThongtinPhieuNhap.add(lblNhaCungCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 110, 30));

        lblMaPhieuNhap.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMaPhieuNhap.setText("Mã Phiếu nhập");
        pnlThongtinPhieuNhap.add(lblMaPhieuNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 110, 30));

        txtMaPhieuNhap.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtMaPhieuNhap.setForeground(new java.awt.Color(102, 0, 0));
        pnlThongtinPhieuNhap.add(txtMaPhieuNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 100, 30));

        lblNhaCungCap2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNhaCungCap2.setText("Ngày nhập");
        pnlThongtinPhieuNhap.add(lblNhaCungCap2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, 30));

        cboNhaCungCap.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        pnlThongtinPhieuNhap.add(cboNhaCungCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 310, 30));

        txtNgayNhap.setForeground(new java.awt.Color(102, 0, 0));
        txtNgayNhap.setDateFormatString("dd/MM/yyyy");
        txtNgayNhap.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        pnlThongtinPhieuNhap.add(txtNgayNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 310, 30));

        tabPNH.add(pnlThongtinPhieuNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 500, 160));

        btnThemPhieuNhap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThemPhieuNhap.setText("Thêm");
        btnThemPhieuNhap.setMaximumSize(new java.awt.Dimension(130, 50));
        btnThemPhieuNhap.setMinimumSize(new java.awt.Dimension(130, 50));
        btnThemPhieuNhap.setPreferredSize(new java.awt.Dimension(130, 50));
        btnThemPhieuNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemPhieuNhapActionPerformed(evt);
            }
        });
        tabPNH.add(btnThemPhieuNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 200, 140, 40));

        btnXoaPhieuNhap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoaPhieuNhap.setText("Xóa");
        btnXoaPhieuNhap.setMaximumSize(new java.awt.Dimension(130, 50));
        btnXoaPhieuNhap.setMinimumSize(new java.awt.Dimension(130, 50));
        btnXoaPhieuNhap.setPreferredSize(new java.awt.Dimension(130, 50));
        btnXoaPhieuNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaPhieuNhapActionPerformed(evt);
            }
        });
        tabPNH.add(btnXoaPhieuNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 200, 140, 40));

        btnNEWPhieuNhap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNEWPhieuNhap.setText("Nhập mới");
        btnNEWPhieuNhap.setMaximumSize(new java.awt.Dimension(130, 50));
        btnNEWPhieuNhap.setMinimumSize(new java.awt.Dimension(130, 50));
        btnNEWPhieuNhap.setPreferredSize(new java.awt.Dimension(130, 50));
        btnNEWPhieuNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNEWPhieuNhapActionPerformed(evt);
            }
        });
        tabPNH.add(btnNEWPhieuNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, 140, 40));

        tblPhieuNhap.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        tblPhieuNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Phiếu Nhập", "Nhà Cung Cấp", "Tổng Tiền", "Ngày Nhập"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPhieuNhap.setGridColor(new java.awt.Color(255, 255, 255));
        tblPhieuNhap.setRowHeight(30);
        tblPhieuNhap.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tblPhieuNhap.setSelectionForeground(new java.awt.Color(0, 0, 204));
        tblPhieuNhap.setShowHorizontalLines(false);
        tblPhieuNhap.setShowVerticalLines(false);
        tblPhieuNhap.getTableHeader().setReorderingAllowed(false);
        tblPhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhieuNhapMouseClicked(evt);
            }
        });
        scrTable4.setViewportView(tblPhieuNhap);

        tabPNH.add(scrTable4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 41, 640, 210));

        pnlThongtinChiTietPNH.setBackground(new java.awt.Color(204, 204, 255));
        pnlThongtinChiTietPNH.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin Phiếu nhập hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 3, 14))); // NOI18N
        pnlThongtinChiTietPNH.setForeground(new java.awt.Color(204, 255, 255));
        pnlThongtinChiTietPNH.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNhaCungCap3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNhaCungCap3.setText("Dịch vụ / Hàng");
        pnlThongtinChiTietPNH.add(lblNhaCungCap3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 110, 30));

        lblMaChiTietPN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMaChiTietPN.setText("Mã Chi tiết PN");
        pnlThongtinChiTietPNH.add(lblMaChiTietPN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 30));

        txtMaChiTietPN.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtMaChiTietPN.setForeground(new java.awt.Color(102, 0, 0));
        pnlThongtinChiTietPNH.add(txtMaChiTietPN, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 110, 30));

        lblSoLuong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSoLuong.setText("Số lượng");
        pnlThongtinChiTietPNH.add(lblSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, 30));

        cboDichVu.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        pnlThongtinChiTietPNH.add(cboDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 210, 30));

        txtDonGia.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtDonGia.setForeground(new java.awt.Color(102, 0, 0));
        txtDonGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDonGiaKeyReleased(evt);
            }
        });
        pnlThongtinChiTietPNH.add(txtDonGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 310, 30));

        lblDonGia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDonGia.setText("Đơn giá");
        pnlThongtinChiTietPNH.add(lblDonGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, 30));

        spnSoLuong.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        spnSoLuong.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999999, 1));
        spnSoLuong.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnSoLuongStateChanged(evt);
            }
        });
        pnlThongtinChiTietPNH.add(spnSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 80, 30));

        lblThanhTien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblThanhTien.setText("Thành tiền");
        pnlThongtinChiTietPNH.add(lblThanhTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 110, 30));

        txtThanhTien.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtThanhTien.setForeground(new java.awt.Color(102, 0, 0));
        pnlThongtinChiTietPNH.add(txtThanhTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 310, 30));

        cboLoaiDV.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        cboLoaiDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiDVActionPerformed(evt);
            }
        });
        pnlThongtinChiTietPNH.add(cboLoaiDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 100, 30));

        tabPNH.add(pnlThongtinChiTietPNH, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 500, 180));

        btnNEWCTPN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNEWCTPN.setText("Nhập mới");
        btnNEWCTPN.setMaximumSize(new java.awt.Dimension(130, 50));
        btnNEWCTPN.setMinimumSize(new java.awt.Dimension(130, 50));
        btnNEWCTPN.setPreferredSize(new java.awt.Dimension(130, 50));
        btnNEWCTPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNEWCTPNActionPerformed(evt);
            }
        });
        tabPNH.add(btnNEWCTPN, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, 140, 40));

        btnThemCTPN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThemCTPN.setText("Thêm");
        btnThemCTPN.setMaximumSize(new java.awt.Dimension(130, 50));
        btnThemCTPN.setMinimumSize(new java.awt.Dimension(130, 50));
        btnThemCTPN.setPreferredSize(new java.awt.Dimension(130, 50));
        btnThemCTPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemCTPNActionPerformed(evt);
            }
        });
        tabPNH.add(btnThemCTPN, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 450, 140, 40));

        btnXoaCTPN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoaCTPN.setText("Xóa");
        btnXoaCTPN.setMaximumSize(new java.awt.Dimension(130, 50));
        btnXoaCTPN.setMinimumSize(new java.awt.Dimension(130, 50));
        btnXoaCTPN.setPreferredSize(new java.awt.Dimension(130, 50));
        btnXoaCTPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaCTPNActionPerformed(evt);
            }
        });
        tabPNH.add(btnXoaCTPN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 450, 140, 40));

        tabbed.addTab("Phiếu nhập hàng", tabPNH);

        pnlRoot.add(tabbed, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 600));

        add(pnlRoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 690));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnThemDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDVActionPerformed
        
    }//GEN-LAST:event_btnThemDVActionPerformed

    private void btnXoaDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaDVActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btnXoaDVActionPerformed

    private void btnNewDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewDVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewDVActionPerformed

    private void tblDSDVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSDVMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tblDSDVMouseClicked

    private void btnThemLOAIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemLOAIActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnThemLOAIActionPerformed

    private void btnXoaLOAIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaLOAIActionPerformed
 
    }//GEN-LAST:event_btnXoaLOAIActionPerformed

    private void btnNEWLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNEWLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNEWLoaiActionPerformed

    private void tblLoaiDVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoaiDVMouseClicked
       
    }//GEN-LAST:event_tblLoaiDVMouseClicked

    private void tblChiTietPNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChiTietPNMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tblChiTietPNMouseClicked

    private void btnThemPhieuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemPhieuNhapActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnThemPhieuNhapActionPerformed

    private void btnXoaPhieuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaPhieuNhapActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnXoaPhieuNhapActionPerformed

    private void btnNEWPhieuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNEWPhieuNhapActionPerformed
        
    }//GEN-LAST:event_btnNEWPhieuNhapActionPerformed

    private void tblPhieuNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhieuNhapMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tblPhieuNhapMouseClicked

    private void txtDonGiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDonGiaKeyReleased
        // TODO add your handling code here:
        try {
            txtThanhTien.setText(Integer.parseInt(txtDonGia.getText()) * (int) spnSoLuong.getValue() + "");

        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtDonGiaKeyReleased

    private void spnSoLuongStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnSoLuongStateChanged
        // TODO add your handling code here:
        try {
            txtThanhTien.setText(Integer.parseInt(txtDonGia.getText()) * (int) spnSoLuong.getValue() + "");

        } catch (Exception e) {
        }

    }//GEN-LAST:event_spnSoLuongStateChanged

    private void cboLoaiDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiDVActionPerformed
        // TODO add your handling code here:
       

    }//GEN-LAST:event_cboLoaiDVActionPerformed

    private void btnNEWCTPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNEWCTPNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNEWCTPNActionPerformed

    private void btnThemCTPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemCTPNActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnThemCTPNActionPerformed

    private void btnXoaCTPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaCTPNActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnXoaCTPNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnNEWCTPN;
    private javax.swing.JButton btnNEWLoai;
    private javax.swing.JButton btnNEWPhieuNhap;
    private javax.swing.JButton btnNewDV;
    private javax.swing.JButton btnThemCTPN;
    private javax.swing.JButton btnThemDV;
    private javax.swing.JButton btnThemLOAI;
    private javax.swing.JButton btnThemPhieuNhap;
    private javax.swing.JButton btnXoaCTPN;
    private javax.swing.JButton btnXoaDV;
    private javax.swing.JButton btnXoaLOAI;
    private javax.swing.JButton btnXoaPhieuNhap;
    private javax.swing.JComboBox<String> cboDichVu;
    private javax.swing.JComboBox<String> cboLoai;
    private javax.swing.JComboBox<String> cboLoaiDV;
    private javax.swing.JComboBox<String> cboNhaCungCap;
    private javax.swing.JCheckBox chkCoSan;
    private javax.swing.JLabel lblDonGia;
    private javax.swing.JLabel lblGiaBan;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JLabel lblHinhmota;
    private javax.swing.JLabel lblLoaiDV;
    private javax.swing.JLabel lblMaChiTietPN;
    private javax.swing.JLabel lblMaDV;
    private javax.swing.JLabel lblMaLoaiDV;
    private javax.swing.JLabel lblMaPhieuNhap;
    private javax.swing.JLabel lblNhaCungCap;
    private javax.swing.JLabel lblNhaCungCap2;
    private javax.swing.JLabel lblNhaCungCap3;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTenDV;
    private javax.swing.JLabel lblTenLoaiDV;
    private javax.swing.JLabel lblThanhTien;
    private javax.swing.JPanel pnlRoot;
    private javax.swing.JPanel pnlThongtinChiTietPNH;
    private javax.swing.JPanel pnlThongtinDV;
    private javax.swing.JPanel pnlThongtinLoaiDV;
    private javax.swing.JPanel pnlThongtinPhieuNhap;
    private javax.swing.JScrollPane scrTable;
    private javax.swing.JScrollPane scrTable1;
    private javax.swing.JScrollPane scrTable2;
    private javax.swing.JScrollPane scrTable3;
    private javax.swing.JScrollPane scrTable4;
    private javax.swing.JSpinner spnSoLuong;
    private javax.swing.JPanel tabDichVu;
    private javax.swing.JPanel tabLoaiDV;
    private javax.swing.JPanel tabPNH;
    private javax.swing.JTabbedPane tabbed;
    private javax.swing.JTable tblChiTietPN;
    private javax.swing.JTable tblDSDV;
    private javax.swing.JTable tblDichvu;
    private javax.swing.JTable tblLoaiDV;
    private javax.swing.JTable tblPhieuNhap;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtMaChiTietPN;
    private javax.swing.JTextField txtMaDV;
    private javax.swing.JTextField txtMaLoaiDV;
    private javax.swing.JTextField txtMaPhieuNhap;
    private com.toedter.calendar.JDateChooser txtNgayNhap;
    private javax.swing.JTextField txtTenDV;
    private javax.swing.JTextField txtTenLoaiDV;
    private javax.swing.JTextField txtThanhTien;
    // End of variables declaration//GEN-END:variables
}
