package com.karaoke.ui;

import com.karaoke.helper.RoundedPanel;
import com.sun.java.swing.plaf.windows.WindowsScrollBarUI;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Thanh
 */
public class QLNguoiDung2 extends javax.swing.JPanel {

    int index = 0;
    ResultSet rs = null;

    public QLNguoiDung2() {
        initComponents();
        String info = "<html> <style>body{\n"
                + "    text-align: left;\n"
                + "    font-family: 'Cambria';\n"
                + "    color: black;\n"
                + "    font-size: 18;\n"
                + "     margin: 5px;\n"
                + "}</style>";
        info += "<h3>NGUYỄN NHẬT THANH</h3>"
                + "<h3>18/05/1992</h3>"
                + "<h3>Username: nhatthanh1805</h3>"
                + "<h3>Phái: Nam</h3>"
                + "<h3>ĐT: 0357991805</h3>"
                + "<h3>CMND: 272693546</h3>"
                + "<h3>Vai trò: Quản lý</h3>"
                + "<h3></h3>"
                + ""
                + "";
        
        int soluong = 22;
        for (int i = 0; i < soluong; i++) {           
            RoundedPanel UserPanel = new RoundedPanel();
            UserPanel.setPreferredSize(new Dimension(400, 295));
            JLabel UserInfo = new JLabel();            
            UserInfo.setText(info);
            UserInfo.setPreferredSize(new Dimension(380, 280));
            UserInfo.setIcon(new ImageIcon(getClass().getResource("/com/karaoke/images/icon/useravatar.png")));
            

            UserPanel.add(UserInfo);
            pnlUser.add(UserPanel);

        }
        if (soluong % 2 == 0) {
            pnlUser.setPreferredSize(new Dimension(1030, 295 * soluong / 2));

        } else {
            pnlUser.setPreferredSize(new Dimension(1030, 295 * soluong / 2));

        }
        pnlUser.repaint();
        pnlUser.revalidate();
        scrUser.setPreferredSize(new Dimension(1050, 325 * 2));
        scrUser.getVerticalScrollBar().setUnitIncrement(20);
        scrUser.setViewportView(pnlUser);
        scrUser.getVerticalScrollBar().setUI(new WindowsScrollBarUI());
        scrUser.getViewport().setOpaque(false);
        
        
       

        //model = (DefaultTableModel) tblBang.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupGioitinh = new javax.swing.ButtonGroup();
        groupTrangthai = new javax.swing.ButtonGroup();
        scrUser = new javax.swing.JScrollPane();
        pnlUser = new javax.swing.JPanel();

        setBackground(new java.awt.Color(0, 51, 51));
        setMaximumSize(new java.awt.Dimension(1050, 690));
        setMinimumSize(new java.awt.Dimension(1050, 690));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1050, 690));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrUser.setBorder(null);
        scrUser.setOpaque(false);
        scrUser.setPreferredSize(new java.awt.Dimension(1050, 690));

        pnlUser.setMinimumSize(new java.awt.Dimension(1050, 690));
        pnlUser.setOpaque(false);
        pnlUser.setPreferredSize(new java.awt.Dimension(1050, 690));
        pnlUser.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 30));
        scrUser.setViewportView(pnlUser);

        add(scrUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup groupGioitinh;
    private javax.swing.ButtonGroup groupTrangthai;
    private javax.swing.JPanel pnlUser;
    private javax.swing.JScrollPane scrUser;
    // End of variables declaration//GEN-END:variables
}
