package com.karaoke.ui;

import java.awt.Color;
import java.awt.Font;
import java.awt.CardLayout;
import javax.swing.JTable;

/**
 *
 * @author Thanh
 */
public class QLPhongJPanel extends javax.swing.JPanel {

    public QLPhongJPanel() {
        initComponents();
       
        ((CardLayout) pnlMain.getLayout()).show(pnlMain, "loaiphong");
        customJTable(tblDanhSach);
        customJTable(tblDanhSach2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlPhong = new javax.swing.JPanel();
        pnlThongtin = new javax.swing.JPanel();
        lblMaPhong = new javax.swing.JLabel();
        txtMaPhong = new javax.swing.JTextField();
        lblLoai = new javax.swing.JLabel();
        cboLoai = new javax.swing.JComboBox<>();
        scrTable = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();
        pnlButtons = new javax.swing.JPanel();
        lblNhapMoi = new javax.swing.JLabel();
        lblThem = new javax.swing.JLabel();
        pnlLoaiPhong = new javax.swing.JPanel();
        pnlThongtin2 = new javax.swing.JPanel();
        lblMaLoaiPhong = new javax.swing.JLabel();
        txtMaLoaiPhong = new javax.swing.JTextField();
        txtTenLoaiPhong = new javax.swing.JTextField();
        lblTenLoaiPhong = new javax.swing.JLabel();
        lblGiaPhong = new javax.swing.JLabel();
        txtGiaPhong = new javax.swing.JTextField();
        scrTable2 = new javax.swing.JScrollPane();
        tblDanhSach2 = new javax.swing.JTable();
        pnlButtons2 = new javax.swing.JPanel();
        lblNhapMoi2 = new javax.swing.JLabel();
        lblThem2 = new javax.swing.JLabel();
        pnlSubmenu = new javax.swing.JPanel();
        lblLoaiPhong = new javax.swing.JLabel();
        lblPhong = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(1050, 690));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1050, 690));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMain.setOpaque(false);
        pnlMain.setLayout(new java.awt.CardLayout());

        pnlPhong.setBackground(new java.awt.Color(0, 0, 0));
        pnlPhong.setMinimumSize(new java.awt.Dimension(1050, 690));
        pnlPhong.setOpaque(false);
        pnlPhong.setPreferredSize(new java.awt.Dimension(1050, 690));
        pnlPhong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlThongtin.setBackground(new java.awt.Color(204, 204, 255));
        pnlThongtin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin phòng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 3, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlThongtin.setForeground(new java.awt.Color(204, 255, 255));
        pnlThongtin.setOpaque(false);
        pnlThongtin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMaPhong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMaPhong.setForeground(new java.awt.Color(255, 255, 255));
        lblMaPhong.setText("Mã phòng");
        pnlThongtin.add(lblMaPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, 30));

        txtMaPhong.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtMaPhong.setForeground(new java.awt.Color(102, 0, 0));
        pnlThongtin.add(txtMaPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 200, 30));

        lblLoai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLoai.setForeground(new java.awt.Color(255, 255, 255));
        lblLoai.setText("Loại phòng");
        pnlThongtin.add(lblLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 30));

        cboLoai.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        pnlThongtin.add(cboLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 200, 30));

        pnlPhong.add(pnlThongtin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 560, 200));

        tblDanhSach.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã phòng", "Loại phòng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDanhSach.setGridColor(new java.awt.Color(255, 255, 255));
        tblDanhSach.setRowHeight(30);
        tblDanhSach.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tblDanhSach.setSelectionForeground(new java.awt.Color(0, 0, 204));
        tblDanhSach.setShowHorizontalLines(false);
        tblDanhSach.setShowVerticalLines(false);
        tblDanhSach.getTableHeader().setReorderingAllowed(false);
        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachMouseClicked(evt);
            }
        });
        scrTable.setViewportView(tblDanhSach);
        if (tblDanhSach.getColumnModel().getColumnCount() > 0) {
            tblDanhSach.getColumnModel().getColumn(0).setMinWidth(50);
            tblDanhSach.getColumnModel().getColumn(0).setMaxWidth(50);
            tblDanhSach.getColumnModel().getColumn(1).setResizable(false);
        }

        pnlPhong.add(scrTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 560, 220));

        pnlButtons.setMaximumSize(new java.awt.Dimension(400, 60));
        pnlButtons.setMinimumSize(new java.awt.Dimension(400, 60));
        pnlButtons.setOpaque(false);
        pnlButtons.setPreferredSize(new java.awt.Dimension(400, 60));
        pnlButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

        lblNhapMoi.setBackground(new java.awt.Color(0, 102, 0));
        lblNhapMoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNhapMoi.setForeground(new java.awt.Color(255, 255, 255));
        lblNhapMoi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNhapMoi.setText("NHẬP MỚI");
        lblNhapMoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNhapMoi.setOpaque(true);
        lblNhapMoi.setPreferredSize(new java.awt.Dimension(120, 40));
        lblNhapMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNhapMoiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNhapMoiMouseExited(evt);
            }
        });
        pnlButtons.add(lblNhapMoi);

        lblThem.setBackground(new java.awt.Color(0, 102, 0));
        lblThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblThem.setForeground(new java.awt.Color(255, 255, 255));
        lblThem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThem.setText("THÊM");
        lblThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblThem.setOpaque(true);
        lblThem.setPreferredSize(new java.awt.Dimension(120, 40));
        lblThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblThemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblThemMouseExited(evt);
            }
        });
        pnlButtons.add(lblThem);

        pnlPhong.add(pnlButtons, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 570, -1, -1));

        pnlMain.add(pnlPhong, "phong");

        pnlLoaiPhong.setBackground(new java.awt.Color(0, 0, 0));
        pnlLoaiPhong.setMinimumSize(new java.awt.Dimension(1050, 690));
        pnlLoaiPhong.setName(""); // NOI18N
        pnlLoaiPhong.setOpaque(false);
        pnlLoaiPhong.setPreferredSize(new java.awt.Dimension(1050, 690));
        pnlLoaiPhong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlThongtin2.setBackground(new java.awt.Color(204, 204, 255));
        pnlThongtin2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin Loại phòng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 3, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlThongtin2.setForeground(new java.awt.Color(204, 255, 255));
        pnlThongtin2.setOpaque(false);
        pnlThongtin2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMaLoaiPhong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMaLoaiPhong.setForeground(new java.awt.Color(255, 255, 255));
        lblMaLoaiPhong.setText("Mã Loại phòng");
        pnlThongtin2.add(lblMaLoaiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, 30));

        txtMaLoaiPhong.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtMaLoaiPhong.setForeground(new java.awt.Color(102, 0, 0));
        pnlThongtin2.add(txtMaLoaiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 200, 30));

        txtTenLoaiPhong.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtTenLoaiPhong.setForeground(new java.awt.Color(102, 0, 0));
        pnlThongtin2.add(txtTenLoaiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 200, 30));

        lblTenLoaiPhong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTenLoaiPhong.setForeground(new java.awt.Color(255, 255, 255));
        lblTenLoaiPhong.setText("Tên Loại phòng");
        pnlThongtin2.add(lblTenLoaiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, 30));

        lblGiaPhong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGiaPhong.setForeground(new java.awt.Color(255, 255, 255));
        lblGiaPhong.setText("Giá phòng");
        pnlThongtin2.add(lblGiaPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, 30));

        txtGiaPhong.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtGiaPhong.setForeground(new java.awt.Color(102, 0, 0));
        pnlThongtin2.add(txtGiaPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 200, 30));

        pnlLoaiPhong.add(pnlThongtin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 560, 200));

        tblDanhSach2.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        tblDanhSach2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Loại phòng", "Tên Loại phòng", "Giá phòng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDanhSach2.setGridColor(new java.awt.Color(255, 255, 255));
        tblDanhSach2.setRowHeight(30);
        tblDanhSach2.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tblDanhSach2.setSelectionForeground(new java.awt.Color(0, 0, 204));
        tblDanhSach2.setShowHorizontalLines(false);
        tblDanhSach2.setShowVerticalLines(false);
        tblDanhSach2.getTableHeader().setReorderingAllowed(false);
        tblDanhSach2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSach2MouseClicked(evt);
            }
        });
        scrTable2.setViewportView(tblDanhSach2);
        if (tblDanhSach2.getColumnModel().getColumnCount() > 0) {
            tblDanhSach2.getColumnModel().getColumn(0).setMinWidth(50);
            tblDanhSach2.getColumnModel().getColumn(0).setMaxWidth(50);
            tblDanhSach2.getColumnModel().getColumn(1).setResizable(false);
            tblDanhSach2.getColumnModel().getColumn(2).setResizable(false);
            tblDanhSach2.getColumnModel().getColumn(3).setResizable(false);
        }

        pnlLoaiPhong.add(scrTable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 560, 220));

        pnlButtons2.setMaximumSize(new java.awt.Dimension(400, 60));
        pnlButtons2.setMinimumSize(new java.awt.Dimension(400, 60));
        pnlButtons2.setOpaque(false);
        pnlButtons2.setPreferredSize(new java.awt.Dimension(400, 60));
        pnlButtons2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

        lblNhapMoi2.setBackground(new java.awt.Color(0, 102, 0));
        lblNhapMoi2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNhapMoi2.setForeground(new java.awt.Color(255, 255, 255));
        lblNhapMoi2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNhapMoi2.setText("NHẬP MỚI");
        lblNhapMoi2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNhapMoi2.setOpaque(true);
        lblNhapMoi2.setPreferredSize(new java.awt.Dimension(120, 40));
        lblNhapMoi2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNhapMoi2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNhapMoi2MouseExited(evt);
            }
        });
        pnlButtons2.add(lblNhapMoi2);

        lblThem2.setBackground(new java.awt.Color(0, 102, 0));
        lblThem2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblThem2.setForeground(new java.awt.Color(255, 255, 255));
        lblThem2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThem2.setText("THÊM");
        lblThem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblThem2.setOpaque(true);
        lblThem2.setPreferredSize(new java.awt.Dimension(120, 40));
        lblThem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblThem2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblThem2MouseExited(evt);
            }
        });
        pnlButtons2.add(lblThem2);

        pnlLoaiPhong.add(pnlButtons2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 570, -1, -1));

        pnlMain.add(pnlLoaiPhong, "loaiphong");

        add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1050, 650));

        pnlSubmenu.setOpaque(false);
        pnlSubmenu.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5));

        lblLoaiPhong.setBackground(new java.awt.Color(255, 255, 255));
        lblLoaiPhong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLoaiPhong.setForeground(new java.awt.Color(0, 0, 204));
        lblLoaiPhong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoaiPhong.setText("QUẢN LÝ LOẠI PHÒNG");
        lblLoaiPhong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLoaiPhong.setMaximumSize(new java.awt.Dimension(190, 20));
        lblLoaiPhong.setMinimumSize(new java.awt.Dimension(190, 20));
        lblLoaiPhong.setOpaque(true);
        lblLoaiPhong.setPreferredSize(new java.awt.Dimension(190, 20));
        lblLoaiPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoaiPhongMouseClicked(evt);
            }
        });
        pnlSubmenu.add(lblLoaiPhong);

        lblPhong.setBackground(new java.awt.Color(0, 0, 204));
        lblPhong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPhong.setForeground(new java.awt.Color(255, 255, 255));
        lblPhong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhong.setText("QUẢN LÝ PHÒNG");
        lblPhong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPhong.setMaximumSize(new java.awt.Dimension(190, 20));
        lblPhong.setMinimumSize(new java.awt.Dimension(190, 20));
        lblPhong.setOpaque(true);
        lblPhong.setPreferredSize(new java.awt.Dimension(190, 20));
        lblPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPhongMouseClicked(evt);
            }
        });
        pnlSubmenu.add(lblPhong);

        add(pnlSubmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void tblDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tblDanhSachMouseClicked

    private void lblNhapMoiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhapMoiMouseEntered
        // TODO add your handling code here:
        lblNhapMoi.setBackground(Color.WHITE);
        lblNhapMoi.setForeground(new Color(0, 102, 0));
    }//GEN-LAST:event_lblNhapMoiMouseEntered

    private void lblNhapMoiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhapMoiMouseExited
        // TODO add your handling code here:
        lblNhapMoi.setBackground(new Color(0, 102, 0));
        lblNhapMoi.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblNhapMoiMouseExited

    private void lblThemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThemMouseEntered
        // TODO add your handling code here:
        lblThem.setBackground(Color.WHITE);
        lblThem.setForeground(new Color(0, 102, 0));
    }//GEN-LAST:event_lblThemMouseEntered

    private void lblThemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThemMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_lblThemMouseExited

    private void lblThem2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThem2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblThem2MouseExited

    private void lblThem2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThem2MouseEntered
        // TODO add your handling code here:
        lblThem2.setBackground(Color.WHITE);
        lblThem2.setForeground(new Color(0, 102, 0));
    }//GEN-LAST:event_lblThem2MouseEntered

    private void lblNhapMoi2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhapMoi2MouseExited
        // TODO add your handling code here:
        lblNhapMoi2.setBackground(new Color(0, 102, 0));
        lblNhapMoi2.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblNhapMoi2MouseExited

    private void lblNhapMoi2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhapMoi2MouseEntered
        // TODO add your handling code here:
        lblNhapMoi2.setBackground(Color.WHITE);
        lblNhapMoi2.setForeground(new Color(0, 102, 0));
    }//GEN-LAST:event_lblNhapMoi2MouseEntered

    private void tblDanhSach2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSach2MouseClicked
        // TODO add your handling code here:
        lblThem.setBackground(new Color(0, 102, 0));
        lblThem.setForeground(Color.WHITE);
    }//GEN-LAST:event_tblDanhSach2MouseClicked

    private void lblPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhongMouseClicked
        // TODO add your handling code here:
        lblPhong.setForeground(new Color(0, 0, 204));
        lblPhong.setBackground(new Color(255, 255, 255));
        lblLoaiPhong.setBackground(new Color(0, 0, 204));
        lblLoaiPhong.setForeground(new Color(255, 255, 255));
        ((CardLayout) pnlMain.getLayout()).show(pnlMain, "phong");
    }//GEN-LAST:event_lblPhongMouseClicked

    private void lblLoaiPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoaiPhongMouseClicked
        // TODO add your handling code here:
        lblPhong.setBackground(new Color(0, 0, 204));
        lblPhong.setForeground(new Color(255, 255, 255));
        lblLoaiPhong.setForeground(new Color(0, 0, 204));
        lblLoaiPhong.setBackground(new Color(255, 255, 255));
        ((CardLayout) pnlMain.getLayout()).show(pnlMain, "loaiphong");
    }//GEN-LAST:event_lblLoaiPhongMouseClicked

    private void customJTable(JTable tbl){
        tbl.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 13));
        tbl.setFont(new Font("Tahoma", Font.PLAIN, 11));
        tbl.getTableHeader().setOpaque(false);
        tbl.getTableHeader().setBackground(new Color(0, 0, 0));
        tbl.getTableHeader().setForeground(new Color(255, 255, 255));
        tbl.setRowHeight(30);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboLoai;
    private javax.swing.JLabel lblGiaPhong;
    private javax.swing.JLabel lblLoai;
    private javax.swing.JLabel lblLoaiPhong;
    private javax.swing.JLabel lblMaLoaiPhong;
    private javax.swing.JLabel lblMaPhong;
    private javax.swing.JLabel lblNhapMoi;
    private javax.swing.JLabel lblNhapMoi2;
    private javax.swing.JLabel lblPhong;
    private javax.swing.JLabel lblTenLoaiPhong;
    private javax.swing.JLabel lblThem;
    private javax.swing.JLabel lblThem2;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlButtons2;
    private javax.swing.JPanel pnlLoaiPhong;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlPhong;
    private javax.swing.JPanel pnlSubmenu;
    private javax.swing.JPanel pnlThongtin;
    private javax.swing.JPanel pnlThongtin2;
    private javax.swing.JScrollPane scrTable;
    private javax.swing.JScrollPane scrTable2;
    private javax.swing.JTable tblDanhSach;
    private javax.swing.JTable tblDanhSach2;
    private javax.swing.JTextField txtGiaPhong;
    private javax.swing.JTextField txtMaLoaiPhong;
    private javax.swing.JTextField txtMaPhong;
    private javax.swing.JTextField txtTenLoaiPhong;
    // End of variables declaration//GEN-END:variables
}
