/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.karaoke.ui;

/**
 *
 * @author PS08241 - Nguyen Nhat Thanh
 */
public class ViewHomeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewHomeJPanel
     */
    public ViewHomeJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlView = new javax.swing.JPanel();
        lblLogoLARGE = new javax.swing.JLabel();
        lblSlogan = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1050, 690));
        setMinimumSize(new java.awt.Dimension(1050, 690));
        setOpaque(false);

        pnlView.setBackground(new java.awt.Color(204, 204, 255));
        pnlView.setMaximumSize(new java.awt.Dimension(1050, 690));
        pnlView.setMinimumSize(new java.awt.Dimension(1050, 690));
        pnlView.setOpaque(false);
        pnlView.setPreferredSize(new java.awt.Dimension(1050, 690));
        pnlView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogoLARGE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogoLARGE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/karaoke/images/icon/Karaoke_LogoLARGE.png"))); // NOI18N
        pnlView.add(lblLogoLARGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1060, 330));

        lblSlogan.setBackground(new java.awt.Color(255, 255, 255));
        lblSlogan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSlogan.setForeground(new java.awt.Color(255, 255, 255));
        lblSlogan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSlogan.setText("PHẦN MỀM QUẢN LÝ PHÒNG HÁT KARAOKE CHUYÊN NGHIỆP");
        pnlView.add(lblSlogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 410, 1050, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlView, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLogoLARGE;
    private javax.swing.JLabel lblSlogan;
    private javax.swing.JPanel pnlView;
    // End of variables declaration//GEN-END:variables
}
