package com.karaoke.ui;

import com.karaoke.helper.JDBCHelper;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author Admin
 */
public class WelcomeJDialog extends javax.swing.JDialog {

    /**
     * Creates new form WelcomeJDialog
     */
    public WelcomeJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        JDBCHelper.executeQuery("SELECT * FROM dbo.Information");
        this.setUndecorated(true);
        this.getRootPane().setOpaque(false);
        this.getContentPane().setBackground(new Color(0, 0, 0, 0));
        this.setBackground(new Color(0, 0, 0, 0));
        initComponents();
        URL url = this.getClass().getResource("/com/karaoke/images/icon/loading.gif");
        ImageIcon imgIcon = new ImageIcon(url);
        lblLoading.setIcon(imgIcon);
        prgBar.setMaximum(100);
        init();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/com/karaoke/images/icon/iconFrame.png")));

    }

    void init() {

        setLocationRelativeTo(null);
        new Timer(30, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int value = prgBar.getValue();
                if (value < 100) {
                    prgBar.setValue(value + 1);
                    if (value == 20) {
                        lblText.setText("Phát triển bởi TT team");
                    }
                    if (value == 50) {
                        lblText.setText("Dự Án 1 - Ứng dụng CNTT - SPRING 2019 ");
                    }
                } else {
                    ((Timer) e.getSource()).stop();
                    WelcomeJDialog.this.dispose();
                    DangNhapJPanel dn = new DangNhapJPanel();
                    dn.setVisible(true);

                }
            }
        }
        ).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        UIManager.put("ProgressBar.background", Color.BLACK);
        UIManager.put("ProgressBar.foreground", Color.RED);
        UIManager.put("ProgressBar.selectionBackground", Color.YELLOW);
        UIManager.put("ProgressBar.selectionForeground", Color.BLUE);
        prgBar = new javax.swing.JProgressBar();
        lblText = new javax.swing.JLabel();
        lblLoading = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/karaoke/images/icon/Karaoke_Logo.png"))); // NOI18N
        lblLogo.setMaximumSize(new java.awt.Dimension(450, 370));
        lblLogo.setMinimumSize(new java.awt.Dimension(450, 370));
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 280));

        prgBar.setBackground(new java.awt.Color(255, 255, 255));
        prgBar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        prgBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        prgBar.setStringPainted(true);
        getContentPane().add(prgBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 450, 30));

        lblText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblText.setForeground(new java.awt.Color(0, 51, 204));
        lblText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblText.setText("Phần Mềm Quản Lý Phòng Karaoke");
        getContentPane().add(lblText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 450, 30));

        lblLoading.setMaximumSize(new java.awt.Dimension(50, 50));
        lblLoading.setMinimumSize(new java.awt.Dimension(50, 50));
        lblLoading.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(lblLoading, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equalsIgnoreCase(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WelcomeJDialog dialog = new WelcomeJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);

            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLoading;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblText;
    private javax.swing.JProgressBar prgBar;
    // End of variables declaration//GEN-END:variables
}
