package com.karaoke.ui;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import javax.swing.Icon;
import javax.swing.JTable;

/**
 *
 * @author Thanh
 */
public class QLDichVuJPanel extends javax.swing.JPanel {

    public QLDichVuJPanel() {
        initComponents();
        customJTable(tblDichvu);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        tabDichVu = new javax.swing.JPanel();
        pnlThongtinDV = new javax.swing.JPanel();
        chkCoSan = new javax.swing.JCheckBox();
        lblMaDV = new javax.swing.JLabel();
        txtMaDV = new javax.swing.JTextField();
        lblLoaiDV = new javax.swing.JLabel();
        cboLoai = new javax.swing.JComboBox<>();
        lblHinh = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        lblGiaBan = new javax.swing.JLabel();
        lblHinhmota = new javax.swing.JLabel();
        lblTenDV = new javax.swing.JLabel();
        txtTenDV = new javax.swing.JTextField();
        scrTable = new javax.swing.JScrollPane();
        tblDichvu = new javax.swing.JTable();
        pnlButtons = new javax.swing.JPanel();
        lblNhapMoi = new javax.swing.JLabel();
        lblThem = new javax.swing.JLabel();
        tabLoaiDV = new javax.swing.JPanel();
        scrTable1 = new javax.swing.JScrollPane();
        tblDSDV = new javax.swing.JTable();
        pnlThongtinLoaiDV = new javax.swing.JPanel();
        txtTenLoaiDV = new javax.swing.JTextField();
        lblTenLoaiDV = new javax.swing.JLabel();
        lblMaLoaiDV = new javax.swing.JLabel();
        txtMaLoaiDV = new javax.swing.JTextField();
        btnThemLOAI = new javax.swing.JButton();
        btnXoaLOAI = new javax.swing.JButton();
        btnNEWLoai = new javax.swing.JButton();
        scrTable2 = new javax.swing.JScrollPane();
        tblLoaiDV = new javax.swing.JTable();
        tabPNH = new javax.swing.JPanel();
        scrTable3 = new javax.swing.JScrollPane();
        tblChiTietPN = new javax.swing.JTable();
        pnlThongtinPhieuNhap = new javax.swing.JPanel();
        lblNhaCungCap = new javax.swing.JLabel();
        lblMaPhieuNhap = new javax.swing.JLabel();
        txtMaPhieuNhap = new javax.swing.JTextField();
        lblNhaCungCap2 = new javax.swing.JLabel();
        cboNhaCungCap = new javax.swing.JComboBox<>();
        txtNgayNhap = new com.toedter.calendar.JDateChooser();
        scrTable4 = new javax.swing.JScrollPane();
        tblPhieuNhap = new javax.swing.JTable();
        pnlThongtinChiTietPNH = new javax.swing.JPanel();
        lblNhaCungCap3 = new javax.swing.JLabel();
        lblMaChiTietPN = new javax.swing.JLabel();
        txtMaChiTietPN = new javax.swing.JTextField();
        lblSoLuong = new javax.swing.JLabel();
        cboDichVu = new javax.swing.JComboBox<>();
        txtDonGia = new javax.swing.JTextField();
        lblDonGia = new javax.swing.JLabel();
        spnSoLuong = new javax.swing.JSpinner();
        lblThanhTien = new javax.swing.JLabel();
        txtThanhTien = new javax.swing.JTextField();
        cboLoaiDV = new javax.swing.JComboBox<>();
        pnlSubmenu = new javax.swing.JPanel();
        lblQLDV = new javax.swing.JLabel();
        lblQLLDV = new javax.swing.JLabel();
        lblQLPNH = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1050, 690));
        setMinimumSize(new java.awt.Dimension(1050, 690));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1050, 690));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMain.setMaximumSize(new java.awt.Dimension(1200, 590));
        pnlMain.setOpaque(false);
        pnlMain.setPreferredSize(new java.awt.Dimension(1050, 690));
        pnlMain.setLayout(new java.awt.CardLayout());

        tabDichVu.setBackground(new java.awt.Color(204, 204, 255));
        tabDichVu.setMaximumSize(new java.awt.Dimension(1200, 590));
        tabDichVu.setMinimumSize(new java.awt.Dimension(1200, 590));
        tabDichVu.setOpaque(false);
        tabDichVu.setPreferredSize(new java.awt.Dimension(1200, 590));
        tabDichVu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlThongtinDV.setBackground(new java.awt.Color(204, 204, 255));
        pnlThongtinDV.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin Dịch vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 3, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlThongtinDV.setForeground(new java.awt.Color(204, 255, 255));
        pnlThongtinDV.setOpaque(false);
        pnlThongtinDV.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chkCoSan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chkCoSan.setForeground(new java.awt.Color(255, 255, 255));
        chkCoSan.setText("Có sẵn");
        chkCoSan.setOpaque(false);
        pnlThongtinDV.add(chkCoSan, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 90, 30));

        lblMaDV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMaDV.setForeground(new java.awt.Color(255, 255, 255));
        lblMaDV.setText("Mã Dịch vụ");
        pnlThongtinDV.add(lblMaDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, 30));

        txtMaDV.setEditable(false);
        txtMaDV.setBackground(new java.awt.Color(255, 255, 255));
        txtMaDV.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtMaDV.setForeground(new java.awt.Color(102, 0, 0));
        pnlThongtinDV.add(txtMaDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 90, 30));

        lblLoaiDV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLoaiDV.setForeground(new java.awt.Color(255, 255, 255));
        lblLoaiDV.setText("Loại Dịch vụ");
        pnlThongtinDV.add(lblLoaiDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, 30));

        cboLoai.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        cboLoai.setForeground(new java.awt.Color(255, 255, 255));
        pnlThongtinDV.add(cboLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 210, 30));

        lblHinh.setBackground(new java.awt.Color(204, 204, 204));
        lblHinh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHinh.setForeground(new java.awt.Color(255, 255, 255));
        lblHinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinh.setText("[BROWSE]");
        lblHinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblHinh.setMaximumSize(new java.awt.Dimension(120, 120));
        lblHinh.setMinimumSize(new java.awt.Dimension(120, 120));
        lblHinh.setOpaque(true);
        lblHinh.setPreferredSize(new java.awt.Dimension(120, 120));
        pnlThongtinDV.add(lblHinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 120, 120));

        txtGiaBan.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtGiaBan.setForeground(new java.awt.Color(102, 0, 0));
        pnlThongtinDV.add(txtGiaBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 210, 30));

        lblGiaBan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGiaBan.setForeground(new java.awt.Color(255, 255, 255));
        lblGiaBan.setText("Giá bán");
        pnlThongtinDV.add(lblGiaBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, 30));

        lblHinhmota.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHinhmota.setForeground(new java.awt.Color(255, 255, 255));
        lblHinhmota.setText("Hình ảnh");
        pnlThongtinDV.add(lblHinhmota, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, 30));

        lblTenDV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTenDV.setForeground(new java.awt.Color(255, 255, 255));
        lblTenDV.setText("Tên Dịch vụ");
        pnlThongtinDV.add(lblTenDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, 30));

        txtTenDV.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtTenDV.setForeground(new java.awt.Color(102, 0, 0));
        pnlThongtinDV.add(txtTenDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 210, 30));

        tabDichVu.add(pnlThongtinDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 1000, 310));

        tblDichvu.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        tblDichvu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã DV", "Tên DV", "Loại DV", "Giá bán", "Tồn kho", "Hình"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDichvu.setGridColor(new java.awt.Color(255, 255, 255));
        tblDichvu.setRowHeight(30);
        tblDichvu.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tblDichvu.setSelectionForeground(new java.awt.Color(0, 0, 204));
        tblDichvu.setShowHorizontalLines(false);
        tblDichvu.setShowVerticalLines(false);
        tblDichvu.getTableHeader().setReorderingAllowed(false);
        tblDichvu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDichvuMouseClicked(evt);
            }
        });
        scrTable.setViewportView(tblDichvu);
        if (tblDichvu.getColumnModel().getColumnCount() > 0) {
            tblDichvu.getColumnModel().getColumn(0).setMinWidth(50);
            tblDichvu.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        tabDichVu.add(scrTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 1000, 240));

        pnlButtons.setMaximumSize(new java.awt.Dimension(400, 60));
        pnlButtons.setMinimumSize(new java.awt.Dimension(400, 60));
        pnlButtons.setOpaque(false);
        pnlButtons.setPreferredSize(new java.awt.Dimension(400, 60));
        pnlButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

        lblNhapMoi.setBackground(new java.awt.Color(0, 102, 0));
        lblNhapMoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNhapMoi.setForeground(new java.awt.Color(255, 255, 255));
        lblNhapMoi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNhapMoi.setText("NHẬP MỚI");
        lblNhapMoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNhapMoi.setOpaque(true);
        lblNhapMoi.setPreferredSize(new java.awt.Dimension(120, 40));
        lblNhapMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNhapMoiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNhapMoiMouseExited(evt);
            }
        });
        pnlButtons.add(lblNhapMoi);

        lblThem.setBackground(new java.awt.Color(0, 102, 0));
        lblThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblThem.setForeground(new java.awt.Color(255, 255, 255));
        lblThem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThem.setText("THÊM");
        lblThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblThem.setOpaque(true);
        lblThem.setPreferredSize(new java.awt.Dimension(120, 40));
        lblThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblThemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblThemMouseExited(evt);
            }
        });
        pnlButtons.add(lblThem);

        tabDichVu.add(pnlButtons, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 580, -1, -1));

        pnlMain.add(tabDichVu, "dichvu");

        tabLoaiDV.setBackground(new java.awt.Color(204, 204, 255));
        tabLoaiDV.setMaximumSize(new java.awt.Dimension(1200, 590));
        tabLoaiDV.setMinimumSize(new java.awt.Dimension(1200, 590));
        tabLoaiDV.setOpaque(false);
        tabLoaiDV.setPreferredSize(new java.awt.Dimension(1200, 590));
        tabLoaiDV.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDSDV.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        tblDSDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Dịch vụ", "Tên Dịch vụ", "Loại Dịch vụ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDSDV.setGridColor(new java.awt.Color(255, 255, 255));
        tblDSDV.setRowHeight(50);
        tblDSDV.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tblDSDV.setSelectionForeground(new java.awt.Color(0, 0, 204));
        tblDSDV.setShowHorizontalLines(false);
        tblDSDV.setShowVerticalLines(false);
        tblDSDV.getTableHeader().setReorderingAllowed(false);
        tblDSDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSDVMouseClicked(evt);
            }
        });
        scrTable1.setViewportView(tblDSDV);

        tabLoaiDV.add(scrTable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 640, 210));

        pnlThongtinLoaiDV.setBackground(new java.awt.Color(204, 204, 255));
        pnlThongtinLoaiDV.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin Loại Dịch vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 3, 14))); // NOI18N
        pnlThongtinLoaiDV.setForeground(new java.awt.Color(204, 255, 255));
        pnlThongtinLoaiDV.setOpaque(false);
        pnlThongtinLoaiDV.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTenLoaiDV.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtTenLoaiDV.setForeground(new java.awt.Color(102, 0, 0));
        pnlThongtinLoaiDV.add(txtTenLoaiDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 260, 30));

        lblTenLoaiDV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTenLoaiDV.setText("Tên Loại Dịch vụ");
        pnlThongtinLoaiDV.add(lblTenLoaiDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, 30));

        lblMaLoaiDV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMaLoaiDV.setText("Mã Loại Dịch vụ");
        pnlThongtinLoaiDV.add(lblMaLoaiDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 110, 30));

        txtMaLoaiDV.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtMaLoaiDV.setForeground(new java.awt.Color(102, 0, 0));
        pnlThongtinLoaiDV.add(txtMaLoaiDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 260, 30));

        tabLoaiDV.add(pnlThongtinLoaiDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 500, 150));

        btnThemLOAI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThemLOAI.setText("Thêm");
        btnThemLOAI.setMaximumSize(new java.awt.Dimension(130, 50));
        btnThemLOAI.setMinimumSize(new java.awt.Dimension(130, 50));
        btnThemLOAI.setPreferredSize(new java.awt.Dimension(130, 50));
        btnThemLOAI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemLOAIActionPerformed(evt);
            }
        });
        tabLoaiDV.add(btnThemLOAI, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 200, 160, -1));

        btnXoaLOAI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoaLOAI.setText("Xóa");
        btnXoaLOAI.setMaximumSize(new java.awt.Dimension(130, 50));
        btnXoaLOAI.setMinimumSize(new java.awt.Dimension(130, 50));
        btnXoaLOAI.setPreferredSize(new java.awt.Dimension(130, 50));
        btnXoaLOAI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaLOAIActionPerformed(evt);
            }
        });
        tabLoaiDV.add(btnXoaLOAI, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 200, 160, -1));

        btnNEWLoai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNEWLoai.setText("Nhập mới");
        btnNEWLoai.setMaximumSize(new java.awt.Dimension(130, 50));
        btnNEWLoai.setMinimumSize(new java.awt.Dimension(130, 50));
        btnNEWLoai.setPreferredSize(new java.awt.Dimension(130, 50));
        btnNEWLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNEWLoaiActionPerformed(evt);
            }
        });
        tabLoaiDV.add(btnNEWLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 160, -1));

        tblLoaiDV.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        tblLoaiDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Loại Dịch vụ", "Tên Loại Dịch vụ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLoaiDV.setGridColor(new java.awt.Color(255, 255, 255));
        tblLoaiDV.setRowHeight(30);
        tblLoaiDV.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tblLoaiDV.setSelectionForeground(new java.awt.Color(0, 0, 204));
        tblLoaiDV.setShowHorizontalLines(false);
        tblLoaiDV.setShowVerticalLines(false);
        tblLoaiDV.getTableHeader().setReorderingAllowed(false);
        tblLoaiDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoaiDVMouseClicked(evt);
            }
        });
        scrTable2.setViewportView(tblLoaiDV);

        tabLoaiDV.add(scrTable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 41, 640, 210));

        pnlMain.add(tabLoaiDV, "loaidv");

        tabPNH.setBackground(new java.awt.Color(204, 204, 255));
        tabPNH.setMaximumSize(new java.awt.Dimension(1200, 590));
        tabPNH.setMinimumSize(new java.awt.Dimension(1200, 590));
        tabPNH.setOpaque(false);
        tabPNH.setPreferredSize(new java.awt.Dimension(1200, 590));
        tabPNH.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblChiTietPN.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        tblChiTietPN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Chi tiết PN", "Tên Dịch vụ", "Đơn giá nhập", "Số lượng", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblChiTietPN.setGridColor(new java.awt.Color(255, 255, 255));
        tblChiTietPN.setRowHeight(30);
        tblChiTietPN.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tblChiTietPN.setSelectionForeground(new java.awt.Color(0, 0, 204));
        tblChiTietPN.setShowHorizontalLines(false);
        tblChiTietPN.setShowVerticalLines(false);
        tblChiTietPN.getTableHeader().setReorderingAllowed(false);
        tblChiTietPN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChiTietPNMouseClicked(evt);
            }
        });
        scrTable3.setViewportView(tblChiTietPN);

        tabPNH.add(scrTable3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 590, 270));

        pnlThongtinPhieuNhap.setBackground(new java.awt.Color(204, 204, 255));
        pnlThongtinPhieuNhap.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin Phiếu nhập hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 3, 14))); // NOI18N
        pnlThongtinPhieuNhap.setForeground(new java.awt.Color(204, 255, 255));
        pnlThongtinPhieuNhap.setOpaque(false);
        pnlThongtinPhieuNhap.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNhaCungCap.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNhaCungCap.setText("Nhà Cung cấp");
        pnlThongtinPhieuNhap.add(lblNhaCungCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 30));

        lblMaPhieuNhap.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMaPhieuNhap.setText("Mã Phiếu nhập");
        pnlThongtinPhieuNhap.add(lblMaPhieuNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 30));

        txtMaPhieuNhap.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtMaPhieuNhap.setForeground(new java.awt.Color(102, 0, 0));
        pnlThongtinPhieuNhap.add(txtMaPhieuNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 140, 30));

        lblNhaCungCap2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNhaCungCap2.setText("Ngày nhập");
        pnlThongtinPhieuNhap.add(lblNhaCungCap2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 110, 30));

        cboNhaCungCap.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        pnlThongtinPhieuNhap.add(cboNhaCungCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 200, 30));

        txtNgayNhap.setForeground(new java.awt.Color(102, 0, 0));
        txtNgayNhap.setDateFormatString("dd/MM/yyyy");
        txtNgayNhap.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        pnlThongtinPhieuNhap.add(txtNgayNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 200, 30));

        tabPNH.add(pnlThongtinPhieuNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 410, 210));

        tblPhieuNhap.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        tblPhieuNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Phiếu Nhập", "Nhà Cung Cấp", "Tổng Tiền", "Ngày Nhập"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPhieuNhap.setGridColor(new java.awt.Color(255, 255, 255));
        tblPhieuNhap.setRowHeight(30);
        tblPhieuNhap.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tblPhieuNhap.setSelectionForeground(new java.awt.Color(0, 0, 204));
        tblPhieuNhap.setShowHorizontalLines(false);
        tblPhieuNhap.setShowVerticalLines(false);
        tblPhieuNhap.getTableHeader().setReorderingAllowed(false);
        tblPhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhieuNhapMouseClicked(evt);
            }
        });
        scrTable4.setViewportView(tblPhieuNhap);

        tabPNH.add(scrTable4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 41, 590, 270));

        pnlThongtinChiTietPNH.setBackground(new java.awt.Color(204, 204, 255));
        pnlThongtinChiTietPNH.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin Phiếu nhập hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 3, 14))); // NOI18N
        pnlThongtinChiTietPNH.setForeground(new java.awt.Color(204, 255, 255));
        pnlThongtinChiTietPNH.setOpaque(false);
        pnlThongtinChiTietPNH.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNhaCungCap3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNhaCungCap3.setText("Dịch vụ / Hàng");
        pnlThongtinChiTietPNH.add(lblNhaCungCap3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 30));

        lblMaChiTietPN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMaChiTietPN.setText("Mã Chi tiết PN");
        pnlThongtinChiTietPNH.add(lblMaChiTietPN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 30));

        txtMaChiTietPN.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtMaChiTietPN.setForeground(new java.awt.Color(102, 0, 0));
        pnlThongtinChiTietPNH.add(txtMaChiTietPN, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 110, 30));

        lblSoLuong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSoLuong.setText("Số lượng");
        pnlThongtinChiTietPNH.add(lblSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 110, 30));

        cboDichVu.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        cboDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDichVuActionPerformed(evt);
            }
        });
        pnlThongtinChiTietPNH.add(cboDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 140, 30));

        txtDonGia.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtDonGia.setForeground(new java.awt.Color(102, 0, 0));
        txtDonGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDonGiaKeyReleased(evt);
            }
        });
        pnlThongtinChiTietPNH.add(txtDonGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 210, 30));

        lblDonGia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDonGia.setText("Đơn giá");
        pnlThongtinChiTietPNH.add(lblDonGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 110, 30));

        spnSoLuong.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        spnSoLuong.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999999, 1));
        spnSoLuong.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnSoLuongStateChanged(evt);
            }
        });
        pnlThongtinChiTietPNH.add(spnSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 80, 30));

        lblThanhTien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblThanhTien.setText("Thành tiền");
        pnlThongtinChiTietPNH.add(lblThanhTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 110, 30));

        txtThanhTien.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtThanhTien.setForeground(new java.awt.Color(102, 0, 0));
        pnlThongtinChiTietPNH.add(txtThanhTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 210, 30));

        cboLoaiDV.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        cboLoaiDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiDVActionPerformed(evt);
            }
        });
        pnlThongtinChiTietPNH.add(cboLoaiDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 100, 30));

        tabPNH.add(pnlThongtinChiTietPNH, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 410, 220));

        pnlMain.add(tabPNH, "phieunhaphang");

        add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 660));

        pnlSubmenu.setOpaque(false);
        pnlSubmenu.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5));

        lblQLDV.setBackground(new java.awt.Color(255, 255, 255));
        lblQLDV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQLDV.setForeground(new java.awt.Color(0, 0, 204));
        lblQLDV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQLDV.setText("QUẢN LÝ DỊCH VỤ");
        lblQLDV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblQLDV.setMaximumSize(new java.awt.Dimension(190, 20));
        lblQLDV.setMinimumSize(new java.awt.Dimension(190, 20));
        lblQLDV.setOpaque(true);
        lblQLDV.setPreferredSize(new java.awt.Dimension(190, 20));
        lblQLDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLDVMouseClicked(evt);
            }
        });
        pnlSubmenu.add(lblQLDV);

        lblQLLDV.setBackground(new java.awt.Color(0, 0, 204));
        lblQLLDV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQLLDV.setForeground(new java.awt.Color(255, 255, 255));
        lblQLLDV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQLLDV.setText("QUẢN LÝ LOẠI DỊCH VỤ");
        lblQLLDV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblQLLDV.setMaximumSize(new java.awt.Dimension(190, 20));
        lblQLLDV.setMinimumSize(new java.awt.Dimension(190, 20));
        lblQLLDV.setOpaque(true);
        lblQLLDV.setPreferredSize(new java.awt.Dimension(190, 20));
        lblQLLDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLLDVMouseClicked(evt);
            }
        });
        pnlSubmenu.add(lblQLLDV);

        lblQLPNH.setBackground(new java.awt.Color(0, 0, 204));
        lblQLPNH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQLPNH.setForeground(new java.awt.Color(255, 255, 255));
        lblQLPNH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQLPNH.setText("QUẢN LÝ PHIẾU NHẬP HÀNG");
        lblQLPNH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblQLPNH.setMaximumSize(new java.awt.Dimension(190, 20));
        lblQLPNH.setMinimumSize(new java.awt.Dimension(190, 20));
        lblQLPNH.setOpaque(true);
        lblQLPNH.setPreferredSize(new java.awt.Dimension(190, 20));
        lblQLPNH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLPNHMouseClicked(evt);
            }
        });
        pnlSubmenu.add(lblQLPNH);

        add(pnlSubmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void tblDSDVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSDVMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tblDSDVMouseClicked

    private void btnThemLOAIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemLOAIActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnThemLOAIActionPerformed

    private void btnXoaLOAIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaLOAIActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnXoaLOAIActionPerformed

    private void btnNEWLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNEWLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNEWLoaiActionPerformed

    private void tblLoaiDVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoaiDVMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tblLoaiDVMouseClicked

    private void tblChiTietPNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChiTietPNMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tblChiTietPNMouseClicked

    private void tblPhieuNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhieuNhapMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tblPhieuNhapMouseClicked

    private void txtDonGiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDonGiaKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtDonGiaKeyReleased

    private void spnSoLuongStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnSoLuongStateChanged
        // TODO add your handling code here:


    }//GEN-LAST:event_spnSoLuongStateChanged

    private void cboLoaiDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiDVActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_cboLoaiDVActionPerformed

    private void cboDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDichVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDichVuActionPerformed

    private void lblThemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThemMouseExited
        // TODO add your handling code here:
        lblThem.setBackground(new Color(0, 102, 0));
        lblThem.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblThemMouseExited

    private void lblThemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThemMouseEntered
        // TODO add your handling code here:
        lblThem.setBackground(Color.WHITE);
        lblThem.setForeground(new Color(0, 102, 0));
    }//GEN-LAST:event_lblThemMouseEntered

    private void lblNhapMoiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhapMoiMouseExited
        // TODO add your handling code here:
        lblNhapMoi.setBackground(new Color(0, 102, 0));
        lblNhapMoi.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblNhapMoiMouseExited

    private void lblNhapMoiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhapMoiMouseEntered
        // TODO add your handling code here:
        lblNhapMoi.setBackground(Color.WHITE);
        lblNhapMoi.setForeground(new Color(0, 102, 0));
    }//GEN-LAST:event_lblNhapMoiMouseEntered

    private void tblDichvuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDichvuMouseClicked

    }//GEN-LAST:event_tblDichvuMouseClicked

    private void lblQLDVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLDVMouseClicked
        // TODO add your handling code here:
        lblQLDV.setForeground(new Color(0, 0, 204));
        lblQLDV.setBackground(new Color(255, 255, 255));
        lblQLLDV.setBackground(new Color(0, 0, 204));
        lblQLLDV.setForeground(new Color(255, 255, 255));
        lblQLPNH.setBackground(new Color(0, 0, 204));
        lblQLPNH.setForeground(new Color(255, 255, 255));
        ((CardLayout) pnlMain.getLayout()).show(pnlMain, "dichvu");
    }//GEN-LAST:event_lblQLDVMouseClicked

    private void lblQLLDVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLLDVMouseClicked
        // TODO add your handling code here:
        lblQLLDV.setForeground(new Color(0, 0, 204));
        lblQLLDV.setBackground(new Color(255, 255, 255));
        lblQLDV.setBackground(new Color(0, 0, 204));
        lblQLDV.setForeground(new Color(255, 255, 255));
        lblQLPNH.setBackground(new Color(0, 0, 204));
        lblQLPNH.setForeground(new Color(255, 255, 255));
        ((CardLayout) pnlMain.getLayout()).show(pnlMain, "loaidv");
    }//GEN-LAST:event_lblQLLDVMouseClicked

    private void lblQLPNHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLPNHMouseClicked
        // TODO add your handling code here:
        lblQLPNH.setForeground(new Color(0, 0, 204));
        lblQLPNH.setBackground(new Color(255, 255, 255));
        lblQLDV.setBackground(new Color(0, 0, 204));
        lblQLDV.setForeground(new Color(255, 255, 255));
        lblQLLDV.setBackground(new Color(0, 0, 204));
        lblQLLDV.setForeground(new Color(255, 255, 255));
        ((CardLayout) pnlMain.getLayout()).show(pnlMain, "phieunhaphang");
    }//GEN-LAST:event_lblQLPNHMouseClicked
    private void customJTable(JTable tbl) {
        tbl.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 13));
        tbl.setFont(new Font("Tahoma", Font.PLAIN, 11));
        tbl.getTableHeader().setOpaque(false);
        tbl.getTableHeader().setBackground(new Color(0, 0, 0));
        tbl.getTableHeader().setForeground(new Color(255, 255, 255));
        tbl.setRowHeight(30);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNEWLoai;
    private javax.swing.JButton btnThemLOAI;
    private javax.swing.JButton btnXoaLOAI;
    private javax.swing.JComboBox<String> cboDichVu;
    private javax.swing.JComboBox<String> cboLoai;
    private javax.swing.JComboBox<String> cboLoaiDV;
    private javax.swing.JComboBox<String> cboNhaCungCap;
    private javax.swing.JCheckBox chkCoSan;
    private javax.swing.JLabel lblDonGia;
    private javax.swing.JLabel lblGiaBan;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JLabel lblHinhmota;
    private javax.swing.JLabel lblLoaiDV;
    private javax.swing.JLabel lblMaChiTietPN;
    private javax.swing.JLabel lblMaDV;
    private javax.swing.JLabel lblMaLoaiDV;
    private javax.swing.JLabel lblMaPhieuNhap;
    private javax.swing.JLabel lblNhaCungCap;
    private javax.swing.JLabel lblNhaCungCap2;
    private javax.swing.JLabel lblNhaCungCap3;
    private javax.swing.JLabel lblNhapMoi;
    private javax.swing.JLabel lblQLDV;
    private javax.swing.JLabel lblQLLDV;
    private javax.swing.JLabel lblQLPNH;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTenDV;
    private javax.swing.JLabel lblTenLoaiDV;
    private javax.swing.JLabel lblThanhTien;
    private javax.swing.JLabel lblThem;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlSubmenu;
    private javax.swing.JPanel pnlThongtinChiTietPNH;
    private javax.swing.JPanel pnlThongtinDV;
    private javax.swing.JPanel pnlThongtinLoaiDV;
    private javax.swing.JPanel pnlThongtinPhieuNhap;
    private javax.swing.JScrollPane scrTable;
    private javax.swing.JScrollPane scrTable1;
    private javax.swing.JScrollPane scrTable2;
    private javax.swing.JScrollPane scrTable3;
    private javax.swing.JScrollPane scrTable4;
    private javax.swing.JSpinner spnSoLuong;
    private javax.swing.JPanel tabDichVu;
    private javax.swing.JPanel tabLoaiDV;
    private javax.swing.JPanel tabPNH;
    private javax.swing.JTable tblChiTietPN;
    private javax.swing.JTable tblDSDV;
    private javax.swing.JTable tblDichvu;
    private javax.swing.JTable tblLoaiDV;
    private javax.swing.JTable tblPhieuNhap;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtMaChiTietPN;
    private javax.swing.JTextField txtMaDV;
    private javax.swing.JTextField txtMaLoaiDV;
    private javax.swing.JTextField txtMaPhieuNhap;
    private com.toedter.calendar.JDateChooser txtNgayNhap;
    private javax.swing.JTextField txtTenDV;
    private javax.swing.JTextField txtTenLoaiDV;
    private javax.swing.JTextField txtThanhTien;
    // End of variables declaration//GEN-END:variables
}
