/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.karaoke.ui;

import java.awt.Color;

/**
 *
 * @author PS08241 - Nguyen Nhat Thanh
 */
public class QLNguoiDung_ThongTin_JDialog extends javax.swing.JDialog {

    /**
     * Creates new form ThongTinNguoiDungJDialog
     */
    public QLNguoiDung_ThongTin_JDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocation(620, 150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupGT = new javax.swing.ButtonGroup();
        btnGroupTT = new javax.swing.ButtonGroup();
        pnlThongtin = new javax.swing.JPanel();
        lblHoten = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        lblDienthoai = new javax.swing.JLabel();
        txtDienThoai = new javax.swing.JTextField();
        lblNgaySinh = new javax.swing.JLabel();
        txtNgaySinh = new com.toedter.calendar.JDateChooser();
        lblCMND = new javax.swing.JLabel();
        txtCMND = new javax.swing.JTextField();
        lblGioitinh = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        lblVaitro = new javax.swing.JLabel();
        cboRole = new javax.swing.JComboBox<>();
        lblTrangthai = new javax.swing.JLabel();
        rdoNghiviec = new javax.swing.JRadioButton();
        rdoActive = new javax.swing.JRadioButton();
        txtHoTen1 = new javax.swing.JTextField();
        lblHoten1 = new javax.swing.JLabel();
        pnlButtons = new javax.swing.JPanel();
        lblNhapMoi = new javax.swing.JLabel();
        lblThem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlThongtin.setBackground(new java.awt.Color(255, 255, 255));
        pnlThongtin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin người dùng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 3, 14), new java.awt.Color(0, 51, 204))); // NOI18N
        pnlThongtin.setForeground(new java.awt.Color(204, 255, 255));
        pnlThongtin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHoten.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHoten.setForeground(new java.awt.Color(0, 0, 204));
        lblHoten.setText("Họ tên");
        pnlThongtin.add(lblHoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 30));

        txtHoTen.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        txtHoTen.setForeground(new java.awt.Color(102, 0, 0));
        pnlThongtin.add(txtHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 220, 30));

        lblDienthoai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDienthoai.setForeground(new java.awt.Color(0, 0, 204));
        lblDienthoai.setText("Điện thoại");
        pnlThongtin.add(lblDienthoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 30));

        txtDienThoai.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        txtDienThoai.setForeground(new java.awt.Color(102, 0, 0));
        pnlThongtin.add(txtDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 220, 30));

        lblNgaySinh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNgaySinh.setForeground(new java.awt.Color(0, 0, 204));
        lblNgaySinh.setText("Ngày sinh");
        pnlThongtin.add(lblNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 30));

        txtNgaySinh.setForeground(new java.awt.Color(102, 0, 0));
        txtNgaySinh.setDateFormatString("dd/MM/yyyy");
        txtNgaySinh.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        pnlThongtin.add(txtNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 220, 30));

        lblCMND.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCMND.setForeground(new java.awt.Color(0, 0, 204));
        lblCMND.setText("CMND");
        pnlThongtin.add(lblCMND, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 30));

        txtCMND.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        txtCMND.setForeground(new java.awt.Color(102, 0, 0));
        pnlThongtin.add(txtCMND, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 220, 30));

        lblGioitinh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGioitinh.setForeground(new java.awt.Color(0, 0, 204));
        lblGioitinh.setText("Giới tính");
        pnlThongtin.add(lblGioitinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 30));

        rdoNam.setBackground(new java.awt.Color(255, 255, 255));
        btnGroupGT.add(rdoNam);
        rdoNam.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        rdoNam.setForeground(new java.awt.Color(0, 0, 204));
        rdoNam.setText("Nam");
        pnlThongtin.add(rdoNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, 30));

        rdoNu.setBackground(new java.awt.Color(255, 255, 255));
        btnGroupGT.add(rdoNu);
        rdoNu.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        rdoNu.setForeground(new java.awt.Color(0, 0, 204));
        rdoNu.setText("Nữ");
        pnlThongtin.add(rdoNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, 30));

        lblVaitro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblVaitro.setForeground(new java.awt.Color(0, 0, 204));
        lblVaitro.setText("Vai trò");
        pnlThongtin.add(lblVaitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, 30));

        cboRole.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        pnlThongtin.add(cboRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 220, 30));

        lblTrangthai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTrangthai.setForeground(new java.awt.Color(0, 0, 204));
        lblTrangthai.setText("Trạng thái");
        pnlThongtin.add(lblTrangthai, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, 30));

        rdoNghiviec.setBackground(new java.awt.Color(255, 255, 255));
        rdoNghiviec.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        rdoNghiviec.setForeground(new java.awt.Color(0, 0, 204));
        rdoNghiviec.setText("Nghỉ việc");
        rdoNghiviec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNghiviecActionPerformed(evt);
            }
        });
        pnlThongtin.add(rdoNghiviec, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, 30));

        rdoActive.setBackground(new java.awt.Color(255, 255, 255));
        btnGroupTT.add(rdoActive);
        rdoActive.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        rdoActive.setForeground(new java.awt.Color(0, 0, 204));
        rdoActive.setText("Đang làm việc");
        pnlThongtin.add(rdoActive, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, 30));

        txtHoTen1.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        txtHoTen1.setForeground(new java.awt.Color(102, 0, 0));
        pnlThongtin.add(txtHoTen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 220, 30));

        lblHoten1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHoten1.setForeground(new java.awt.Color(0, 0, 204));
        lblHoten1.setText("Username");
        pnlThongtin.add(lblHoten1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 30));

        pnlButtons.setMaximumSize(new java.awt.Dimension(400, 60));
        pnlButtons.setMinimumSize(new java.awt.Dimension(400, 60));
        pnlButtons.setOpaque(false);
        pnlButtons.setPreferredSize(new java.awt.Dimension(400, 60));
        pnlButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

        lblNhapMoi.setBackground(new java.awt.Color(0, 102, 0));
        lblNhapMoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNhapMoi.setForeground(new java.awt.Color(255, 255, 255));
        lblNhapMoi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNhapMoi.setText("NHẬP MỚI");
        lblNhapMoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNhapMoi.setOpaque(true);
        lblNhapMoi.setPreferredSize(new java.awt.Dimension(120, 40));
        lblNhapMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNhapMoiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNhapMoiMouseExited(evt);
            }
        });
        pnlButtons.add(lblNhapMoi);

        lblThem.setBackground(new java.awt.Color(0, 102, 0));
        lblThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblThem.setForeground(new java.awt.Color(255, 255, 255));
        lblThem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThem.setText("THÊM");
        lblThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblThem.setOpaque(true);
        lblThem.setPreferredSize(new java.awt.Dimension(120, 40));
        lblThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblThemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblThemMouseExited(evt);
            }
        });
        pnlButtons.add(lblThem);

        pnlThongtin.add(pnlButtons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 380, 50));

        getContentPane().add(pnlThongtin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdoNghiviecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNghiviecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNghiviecActionPerformed

    private void lblNhapMoiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhapMoiMouseEntered
        // TODO add your handling code here:
        lblNhapMoi.setBackground(Color.WHITE);
        lblNhapMoi.setForeground(new Color(0, 102, 0));
    }//GEN-LAST:event_lblNhapMoiMouseEntered

    private void lblNhapMoiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhapMoiMouseExited
        // TODO add your handling code here:
        lblNhapMoi.setBackground(new Color(0, 102, 0));
        lblNhapMoi.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblNhapMoiMouseExited

    private void lblThemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThemMouseEntered
        // TODO add your handling code here:
        lblThem.setBackground(Color.WHITE);
        lblThem.setForeground(new Color(0, 102, 0));
    }//GEN-LAST:event_lblThemMouseEntered

    private void lblThemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThemMouseExited
        // TODO add your handling code here:
        lblThem.setBackground(new Color(0, 102, 0));
        lblThem.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblThemMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLNguoiDung_ThongTin_JDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLNguoiDung_ThongTin_JDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLNguoiDung_ThongTin_JDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLNguoiDung_ThongTin_JDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QLNguoiDung_ThongTin_JDialog dialog = new QLNguoiDung_ThongTin_JDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupGT;
    private javax.swing.ButtonGroup btnGroupTT;
    private javax.swing.JComboBox<String> cboRole;
    private javax.swing.JLabel lblCMND;
    private javax.swing.JLabel lblDienthoai;
    private javax.swing.JLabel lblGioitinh;
    private javax.swing.JLabel lblHoten;
    private javax.swing.JLabel lblHoten1;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblNhapMoi;
    private javax.swing.JLabel lblThem;
    private javax.swing.JLabel lblTrangthai;
    private javax.swing.JLabel lblVaitro;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlThongtin;
    private javax.swing.JRadioButton rdoActive;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNghiviec;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtDienThoai;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtHoTen1;
    private com.toedter.calendar.JDateChooser txtNgaySinh;
    // End of variables declaration//GEN-END:variables
}
