package com.karaoke.ui.quanly;

import com.karaoke.dao.UsersDAO;
import com.karaoke.helper.RoundedPanel;
import com.karaoke.helper.XuLy;
import com.karaoke.model.Users;
import com.sun.java.swing.plaf.windows.WindowsScrollBarUI;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author Thanh
 */
public class QLNguoiDung extends javax.swing.JPanel {

    List<Users> listU = new ArrayList<>();
    List<RoundedPanel> listPanel = new ArrayList<>();
    int soluong = 0;
    ResultSet rs = null;

    public QLNguoiDung() {
        initComponents();
        loadUsers();
        if (soluong % 2 == 0) {
            pnlUser.setPreferredSize(new Dimension(1030, 125 * soluong / 2));

        } else {
            pnlUser.setPreferredSize(new Dimension(1030, 125 * soluong / 2));

        }
        pnlUser.repaint();
        pnlUser.revalidate();
        scrUser.setPreferredSize(new Dimension(1050, 325 * 2));
        scrUser.getVerticalScrollBar().setUnitIncrement(20);
        scrUser.setViewportView(pnlUser);
        scrUser.getVerticalScrollBar().setUI(new WindowsScrollBarUI());
        scrUser.getViewport().setOpaque(false);

        //model = (DefaultTableModel) tblBang.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupGioitinh = new javax.swing.ButtonGroup();
        groupTrangthai = new javax.swing.ButtonGroup();
        scrUser = new javax.swing.JScrollPane();
        pnlUser = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnThemNguoiDung = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 51, 51));
        setMaximumSize(new java.awt.Dimension(1050, 690));
        setMinimumSize(new java.awt.Dimension(1050, 690));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1050, 690));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrUser.setBorder(null);
        scrUser.setOpaque(false);
        scrUser.setPreferredSize(new java.awt.Dimension(1050, 690));

        pnlUser.setMinimumSize(new java.awt.Dimension(1050, 690));
        pnlUser.setOpaque(false);
        pnlUser.setPreferredSize(new java.awt.Dimension(1050, 690));
        pnlUser.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 30));
        scrUser.setViewportView(pnlUser);

        add(scrUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, 650));

        txtSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSearch.setBorder(null);
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 240, 30));

        btnThemNguoiDung.setBackground(new java.awt.Color(255, 255, 255));
        btnThemNguoiDung.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThemNguoiDung.setText("Thêm Người Dùng");
        btnThemNguoiDung.setFocusPainted(false);
        btnThemNguoiDung.setFocusable(false);
        btnThemNguoiDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNguoiDungActionPerformed(evt);
            }
        });
        add(btnThemNguoiDung, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 140, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemNguoiDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNguoiDungActionPerformed
        // TODO add your handling code here:
        new QLNguoiDung_ThongTin_JDialog(null, true, null).setVisible(true);
        loadUsers();

    }//GEN-LAST:event_btnThemNguoiDungActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        for (RoundedPanel pnl : listPanel) {
            //JOptionPane.showMessageDialog(this, pnl.getName());

            if (XuLy.khongDau(pnl.getName().toLowerCase()).contains(XuLy.khongDau(txtSearch.getText().toLowerCase().trim()))) {
                pnl.setBackground(Color.YELLOW);
            } else {
                pnl.setBackground(Color.WHITE);

            }
        }
        if (txtSearch.getText().trim().equals("")) {
            for (RoundedPanel pnl : listPanel) {
                //JOptionPane.showMessageDialog(this, pnl.getName());
                pnl.setBackground(Color.WHITE);

            }
        }
    }//GEN-LAST:event_txtSearchKeyReleased
    private void loadUsers() {
        pnlUser.removeAll();
        listU = new UsersDAO().select();
        int i = 0;
        for (Users u : listU) {
            i++;
            RoundedPanel UserPanel = new RoundedPanel();
            UserPanel.setBackground(Color.WHITE);
            UserPanel.setName(u.getUsername() + " " + u.getHoTen() + " " + u.getEmail() + " " + u.getSoDT());
            UserPanel.setPreferredSize(new Dimension(300, 125));
            JLabel UserInfo = new JLabel();
            UserInfo.setHorizontalAlignment(SwingConstants.CENTER);
            String info = "<html> <center><font size = 5 color = blue>" + u.getMaUser() + "<br>" + u.getHoTen().toUpperCase() + "</font><br>";
            if (u.isRole()) {
                info += "<b><font color = red>[Quản lý - Admin]</font></b>";
            } else {
                info += "<b>[Nhân viên]</b>";
            }
            if (!u.isActive()) {
                info += "<br><font color = red>Đã nghỉ việc</";
            }
            info += "<br>Username: <b>" + u.getUsername();
            UserInfo.setText(info);
            UserInfo.setPreferredSize(new Dimension(300, 120));
            UserPanel.add(UserInfo);
            UserPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            UserPanel.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    new QLNguoiDung_ThongTin_JDialog(null, true, u.getMaUser()).setVisible(true);
                    loadUsers();

                }
            });
            pnlUser.add(UserPanel);
            listPanel.add(UserPanel);
            soluong = i;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemNguoiDung;
    private javax.swing.ButtonGroup groupGioitinh;
    private javax.swing.ButtonGroup groupTrangthai;
    private javax.swing.JPanel pnlUser;
    private javax.swing.JScrollPane scrUser;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
