/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.karaoke.ui.quanly;

import com.karaoke.dao.VoucherDAO;
import com.karaoke.helper.JDBCHelper;
import com.karaoke.helper.JOptionPaneHelper;
import com.karaoke.model.Voucher;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Locale;

/**
 *
 * @author PS08241 - Nguyen Nhat Thanh
 */
public class QLVoucher_ThongTin_JDialog extends javax.swing.JDialog {

    String codevoucher;

    /**
     * Creates new form ThongTinNguoiDungJDialog
     */
    public QLVoucher_ThongTin_JDialog(java.awt.Frame parent, boolean modal, String codevoucher) {
        super(parent, modal);
        initComponents();
        this.codevoucher = codevoucher;
        setLocationRelativeTo(parent);
        if (codevoucher != null) {
            try {
                loadData();
                btnThem.setText("Cập nhật");
            } catch (SQLException e) {
            }
        }
        txtHanDung.setLocale(new Locale("vi", "VIETNAM"));
        txtHanDung.setDateFormatString("dd/MM/yyyy");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupGT = new javax.swing.ButtonGroup();
        btnGroupTT = new javax.swing.ButtonGroup();
        pnlThongtin = new javax.swing.JPanel();
        lblHanDung = new javax.swing.JLabel();
        txtHanDung = new com.toedter.calendar.JDateChooser();
        txtCodevoucher = new javax.swing.JTextField();
        lblHoten1 = new javax.swing.JLabel();
        btnNew = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        lblHoten2 = new javax.swing.JLabel();
        spnTriGia = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thông tin người dùng");
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlThongtin.setBackground(new java.awt.Color(255, 255, 255));
        pnlThongtin.setForeground(new java.awt.Color(204, 255, 255));
        pnlThongtin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHanDung.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHanDung.setForeground(new java.awt.Color(0, 0, 204));
        lblHanDung.setText("Hạn dùng");
        pnlThongtin.add(lblHanDung, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 30));

        txtHanDung.setDateFormatString("dd/MM/yyyy");
        txtHanDung.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        pnlThongtin.add(txtHanDung, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 220, 30));

        txtCodevoucher.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        pnlThongtin.add(txtCodevoucher, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 220, 30));

        lblHoten1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHoten1.setForeground(new java.awt.Color(0, 0, 204));
        lblHoten1.setText("Codevoucher");
        pnlThongtin.add(lblHoten1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 30));

        btnNew.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNew.setForeground(new java.awt.Color(0, 0, 204));
        btnNew.setText("Nhập mới");
        btnNew.setMaximumSize(new java.awt.Dimension(130, 50));
        btnNew.setMinimumSize(new java.awt.Dimension(130, 50));
        btnNew.setPreferredSize(new java.awt.Dimension(130, 50));
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        pnlThongtin.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 110, 40));

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(0, 0, 204));
        btnThem.setText("Thêm");
        btnThem.setMaximumSize(new java.awt.Dimension(130, 50));
        btnThem.setMinimumSize(new java.awt.Dimension(130, 50));
        btnThem.setPreferredSize(new java.awt.Dimension(130, 50));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        pnlThongtin.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 110, 40));

        lblHoten2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHoten2.setForeground(new java.awt.Color(0, 0, 204));
        lblHoten2.setText("Trị giá");
        pnlThongtin.add(lblHoten2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 30));

        spnTriGia.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        pnlThongtin.add(spnTriGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 60, 30));

        getContentPane().add(pnlThongtin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
            // TODO add your handling code here:
            if (btnThem.getText().equals("Thêm")) {
                addV();
            } else {
                editV();
            }
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnNewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLVoucher_ThongTin_JDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLVoucher_ThongTin_JDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLVoucher_ThongTin_JDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLVoucher_ThongTin_JDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QLVoucher_ThongTin_JDialog dialog = new QLVoucher_ThongTin_JDialog(new javax.swing.JFrame(), true, "thanh");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private boolean checkInput() throws SQLException {
        if (txtCodevoucher.getText().length()>12) {
            JOptionPaneHelper.popup("loi", this, "Độ dài Code dưới 12 kí tự", "LỖI");
            txtCodevoucher.requestFocus();
            return false;
        }
        if (txtHanDung.getDate() == null) {
            JOptionPaneHelper.popup("loi", this, "Chưa chọn/chưa nhập ngày sinh", "LỖI");
            txtHanDung.requestFocus();
            return false;
        }
        return true;

    }

    private void loadData() throws SQLException {
        ResultSet rs = JDBCHelper.executeQuery("SELECT * FROM dbo.Voucher WHERE codevoucher = ?", codevoucher);
        if (rs.next()) {
            txtCodevoucher.setText(rs.getString("codevoucher"));
            spnTriGia.setValue((int) rs.getInt("triGia"));
            txtHanDung.setDate(rs.getDate("hanDung"));
        }
    }

    private void addV() throws SQLException {
        if (checkInput()) {
            Voucher v = new Voucher();
            v.setCodevoucher(txtCodevoucher.getText());
            v.setTriGia((int) spnTriGia.getValue());
            v.setHanDung(new SimpleDateFormat("yyyy-MM-dd").format(txtHanDung.getDate()));
            new VoucherDAO().insert(v);
            JOptionPaneHelper.popup("ok", this, "Thêm  thành công", "THÊM USER");
            dispose();

        }
    }

    private void editV() throws SQLException {
        if (checkInput()) {
            Voucher v = new Voucher();
            v.setCodevoucher(txtCodevoucher.getText());
            v.setTriGia((int) spnTriGia.getValue());
            v.setHanDung(new SimpleDateFormat("yyyy-MM-dd").format(txtHanDung.getDate()));
            new VoucherDAO().update(v, codevoucher);
            JOptionPaneHelper.popup("ok", this, "Cập nhật thành công", "THÊM USER");
            dispose();

        }
    }

    private void clear() {
        txtCodevoucher.setText("");
        txtHanDung.setDate(null);
        spnTriGia.setValue((int) 0);
        btnThem.setText("Thêm");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupGT;
    private javax.swing.ButtonGroup btnGroupTT;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnThem;
    private javax.swing.JLabel lblHanDung;
    private javax.swing.JLabel lblHoten1;
    private javax.swing.JLabel lblHoten2;
    private javax.swing.JPanel pnlThongtin;
    private javax.swing.JSpinner spnTriGia;
    private javax.swing.JTextField txtCodevoucher;
    private com.toedter.calendar.JDateChooser txtHanDung;
    // End of variables declaration//GEN-END:variables
}
