package com.karaoke.ui.quanly;

import com.karaoke.dao.VoucherDAO;
import com.karaoke.helper.RoundedPanel;
import com.karaoke.helper.XuLy;
import com.karaoke.model.Users;
import com.karaoke.model.Voucher;
import com.sun.java.swing.plaf.windows.WindowsScrollBarUI;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author Thanh
 */
public class QLVoucherJPanel extends javax.swing.JPanel {

    List<Voucher> listV = new ArrayList<>();
    List<RoundedPanel> listPanel = new ArrayList<>();
    int soluong = 0;
    ResultSet rs = null;

    public QLVoucherJPanel() {
        initComponents();
        loadVouchers();
        if (soluong % 2 == 0) {
            pnlVoucher.setPreferredSize(new Dimension(1030, 125 * soluong / 2));

        } else {
            pnlVoucher.setPreferredSize(new Dimension(1030, 125 * soluong / 2));

        }
        pnlVoucher.repaint();
        pnlVoucher.revalidate();
        scrVoucher.setPreferredSize(new Dimension(1050, 325 * 2));
        scrVoucher.getVerticalScrollBar().setUnitIncrement(20);
        scrVoucher.setViewportView(pnlVoucher);
        scrVoucher.getVerticalScrollBar().setUI(new WindowsScrollBarUI());
        scrVoucher.getViewport().setOpaque(false);

        //model = (DefaultTableModel) tblBang.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupGioitinh = new javax.swing.ButtonGroup();
        groupTrangthai = new javax.swing.ButtonGroup();
        scrVoucher = new javax.swing.JScrollPane();
        pnlVoucher = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnThemVoucher = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 51, 51));
        setMaximumSize(new java.awt.Dimension(1050, 690));
        setMinimumSize(new java.awt.Dimension(1050, 690));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1050, 690));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrVoucher.setBorder(null);
        scrVoucher.setOpaque(false);
        scrVoucher.setPreferredSize(new java.awt.Dimension(1050, 690));

        pnlVoucher.setMinimumSize(new java.awt.Dimension(1050, 690));
        pnlVoucher.setOpaque(false);
        pnlVoucher.setPreferredSize(new java.awt.Dimension(1050, 690));
        pnlVoucher.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 30));
        scrVoucher.setViewportView(pnlVoucher);

        add(scrVoucher, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, 650));

        txtSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSearch.setBorder(null);
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 240, 30));

        btnThemVoucher.setBackground(new java.awt.Color(255, 255, 255));
        btnThemVoucher.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThemVoucher.setText("Thêm Voucher");
        btnThemVoucher.setFocusPainted(false);
        btnThemVoucher.setFocusable(false);
        btnThemVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemVoucherActionPerformed(evt);
            }
        });
        add(btnThemVoucher, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 140, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemVoucherActionPerformed
        // TODO add your handling code here:
        new QLVoucher_ThongTin_JDialog(null, true, null).setVisible(true);
        loadVouchers();

    }//GEN-LAST:event_btnThemVoucherActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        for (RoundedPanel pnl : listPanel) {
            //JOptionPane.showMessageDialog(this, pnl.getName());

            if (XuLy.khongDau(pnl.getName().toLowerCase()).contains(XuLy.khongDau(txtSearch.getText().toLowerCase().trim()))) {
                pnl.setBackground(Color.YELLOW);
            } else {
                pnl.setBackground(Color.WHITE);

            }
        }
        if (txtSearch.getText().trim().equals("")) {
            for (RoundedPanel pnl : listPanel) {
                //JOptionPane.showMessageDialog(this, pnl.getName());
                pnl.setBackground(Color.WHITE);

            }
        }
    }//GEN-LAST:event_txtSearchKeyReleased
    private void loadVouchers() {
        pnlVoucher.removeAll();
        listV = new VoucherDAO().select();
        int i = 0;
        for (Voucher v : listV) {
            i++;
            RoundedPanel VoucherPanel = new RoundedPanel();
            VoucherPanel.setBackground(Color.WHITE);
            VoucherPanel.setName(v.getCodevoucher());
            VoucherPanel.setPreferredSize(new Dimension(300, 125));
            JLabel VoucherInfo = new JLabel();
            VoucherInfo.setHorizontalAlignment(SwingConstants.CENTER);
            String info = "<html> <center><font size = 5 color = blue>" + v.getCodevoucher() + "<br>" + v.getTriGia() + "%</font><br>";
            info += "Hạn dùng: " + XuLy.convertDate(v.getHanDung());

            VoucherInfo.setText(info);
            VoucherInfo.setPreferredSize(new Dimension(300, 120));
            VoucherPanel.add(VoucherInfo);
            VoucherPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            VoucherPanel.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    new QLVoucher_ThongTin_JDialog(null, true, v.getCodevoucher()).setVisible(true);
                    loadVouchers();

                }
            });
            pnlVoucher.add(VoucherPanel);
            listPanel.add(VoucherPanel);
            soluong = i;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemVoucher;
    private javax.swing.ButtonGroup groupGioitinh;
    private javax.swing.ButtonGroup groupTrangthai;
    private javax.swing.JPanel pnlVoucher;
    private javax.swing.JScrollPane scrVoucher;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
